// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: msg_thruster.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_msg_5fthruster_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_msg_5fthruster_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_msg_5fthruster_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_msg_5fthruster_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_msg_5fthruster_2eproto;
namespace thruster {
class Data;
struct DataDefaultTypeInternal;
extern DataDefaultTypeInternal _Data_default_instance_;
class OutMsg;
struct OutMsgDefaultTypeInternal;
extern OutMsgDefaultTypeInternal _OutMsg_default_instance_;
}  // namespace thruster
PROTOBUF_NAMESPACE_OPEN
template<> ::thruster::Data* Arena::CreateMaybeMessage<::thruster::Data>(Arena*);
template<> ::thruster::OutMsg* Arena::CreateMaybeMessage<::thruster::OutMsg>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace thruster {

enum Status : int {
  NORMAL = 0,
  STALL = 1,
  MOTOR_OVERHEAT = 2,
  MOS_OVERHEAT = 4,
  OVER_CURRENT = 8,
  COMM_FAULT = 16,
  MOTOR_TEMP_ERROR = 32,
  MOS_TEMP_ALARM = 64,
  OVER_VOLTAGE = 128,
  UNDER_VOLTAGE = 256,
  CIRCUIT_FAULT = 512,
  CHARGING = 1024,
  FAN_FAULT = 2048,
  OTHER = 1073741824,
  Status_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::min(),
  Status_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::max()
};
bool Status_IsValid(int value);
constexpr Status Status_MIN = NORMAL;
constexpr Status Status_MAX = OTHER;
constexpr int Status_ARRAYSIZE = Status_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* Status_descriptor();
template<typename T>
inline const std::string& Status_Name(T enum_t_value) {
  static_assert(::std::is_same<T, Status>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function Status_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    Status_descriptor(), enum_t_value);
}
inline bool Status_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, Status* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<Status>(
    Status_descriptor(), name, value);
}
// ===================================================================

class Data final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:thruster.Data) */ {
 public:
  inline Data() : Data(nullptr) {}
  ~Data() override;
  explicit PROTOBUF_CONSTEXPR Data(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  Data(const Data& from);
  Data(Data&& from) noexcept
    : Data() {
    *this = ::std::move(from);
  }

  inline Data& operator=(const Data& from) {
    CopyFrom(from);
    return *this;
  }
  inline Data& operator=(Data&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Data& default_instance() {
    return *internal_default_instance();
  }
  static inline const Data* internal_default_instance() {
    return reinterpret_cast<const Data*>(
               &_Data_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(Data& a, Data& b) {
    a.Swap(&b);
  }
  inline void Swap(Data* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Data* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Data* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<Data>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const Data& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const Data& from) {
    Data::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Data* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "thruster.Data";
  }
  protected:
  explicit Data(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kStatusFieldNumber = 1,
    kErrorCodeFieldNumber = 2,
    kRpmFieldNumber = 3,
    kAngleFieldNumber = 4,
    kPowerFieldNumber = 5,
    kBusVoltageFieldNumber = 6,
    kBusCurrentFieldNumber = 7,
    kPhaseCurrentFieldNumber = 8,
    kMotorTempFieldNumber = 9,
    kMosTempFieldNumber = 10,
    kTempFieldNumber = 11,
    kRunTimeFieldNumber = 12,
    kSumRunTimeFieldNumber = 13,
  };
  // uint32 status = 1;
  void clear_status();
  uint32_t status() const;
  void set_status(uint32_t value);
  private:
  uint32_t _internal_status() const;
  void _internal_set_status(uint32_t value);
  public:

  // uint32 error_code = 2;
  void clear_error_code();
  uint32_t error_code() const;
  void set_error_code(uint32_t value);
  private:
  uint32_t _internal_error_code() const;
  void _internal_set_error_code(uint32_t value);
  public:

  // int32 rpm = 3;
  void clear_rpm();
  int32_t rpm() const;
  void set_rpm(int32_t value);
  private:
  int32_t _internal_rpm() const;
  void _internal_set_rpm(int32_t value);
  public:

  // int32 angle = 4;
  void clear_angle();
  int32_t angle() const;
  void set_angle(int32_t value);
  private:
  int32_t _internal_angle() const;
  void _internal_set_angle(int32_t value);
  public:

  // int32 power = 5;
  void clear_power();
  int32_t power() const;
  void set_power(int32_t value);
  private:
  int32_t _internal_power() const;
  void _internal_set_power(int32_t value);
  public:

  // uint32 bus_voltage = 6;
  void clear_bus_voltage();
  uint32_t bus_voltage() const;
  void set_bus_voltage(uint32_t value);
  private:
  uint32_t _internal_bus_voltage() const;
  void _internal_set_bus_voltage(uint32_t value);
  public:

  // int32 bus_current = 7;
  void clear_bus_current();
  int32_t bus_current() const;
  void set_bus_current(int32_t value);
  private:
  int32_t _internal_bus_current() const;
  void _internal_set_bus_current(int32_t value);
  public:

  // int32 phase_current = 8;
  void clear_phase_current();
  int32_t phase_current() const;
  void set_phase_current(int32_t value);
  private:
  int32_t _internal_phase_current() const;
  void _internal_set_phase_current(int32_t value);
  public:

  // int32 motor_temp = 9;
  void clear_motor_temp();
  int32_t motor_temp() const;
  void set_motor_temp(int32_t value);
  private:
  int32_t _internal_motor_temp() const;
  void _internal_set_motor_temp(int32_t value);
  public:

  // int32 mos_temp = 10;
  void clear_mos_temp();
  int32_t mos_temp() const;
  void set_mos_temp(int32_t value);
  private:
  int32_t _internal_mos_temp() const;
  void _internal_set_mos_temp(int32_t value);
  public:

  // int32 _temp = 11;
  void clear__temp();
  int32_t _temp() const;
  void set__temp(int32_t value);
  private:
  int32_t _internal__temp() const;
  void _internal_set__temp(int32_t value);
  public:

  // uint32 run_time = 12;
  void clear_run_time();
  uint32_t run_time() const;
  void set_run_time(uint32_t value);
  private:
  uint32_t _internal_run_time() const;
  void _internal_set_run_time(uint32_t value);
  public:

  // uint32 sum_run_time = 13;
  void clear_sum_run_time();
  uint32_t sum_run_time() const;
  void set_sum_run_time(uint32_t value);
  private:
  uint32_t _internal_sum_run_time() const;
  void _internal_set_sum_run_time(uint32_t value);
  public:

  // @@protoc_insertion_point(class_scope:thruster.Data)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    uint32_t status_;
    uint32_t error_code_;
    int32_t rpm_;
    int32_t angle_;
    int32_t power_;
    uint32_t bus_voltage_;
    int32_t bus_current_;
    int32_t phase_current_;
    int32_t motor_temp_;
    int32_t mos_temp_;
    int32_t _temp_;
    uint32_t run_time_;
    uint32_t sum_run_time_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_msg_5fthruster_2eproto;
};
// -------------------------------------------------------------------

class OutMsg final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:thruster.OutMsg) */ {
 public:
  inline OutMsg() : OutMsg(nullptr) {}
  ~OutMsg() override;
  explicit PROTOBUF_CONSTEXPR OutMsg(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  OutMsg(const OutMsg& from);
  OutMsg(OutMsg&& from) noexcept
    : OutMsg() {
    *this = ::std::move(from);
  }

  inline OutMsg& operator=(const OutMsg& from) {
    CopyFrom(from);
    return *this;
  }
  inline OutMsg& operator=(OutMsg&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const OutMsg& default_instance() {
    return *internal_default_instance();
  }
  static inline const OutMsg* internal_default_instance() {
    return reinterpret_cast<const OutMsg*>(
               &_OutMsg_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(OutMsg& a, OutMsg& b) {
    a.Swap(&b);
  }
  inline void Swap(OutMsg* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(OutMsg* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  OutMsg* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<OutMsg>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const OutMsg& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const OutMsg& from) {
    OutMsg::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(OutMsg* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "thruster.OutMsg";
  }
  protected:
  explicit OutMsg(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kThrustersFieldNumber = 3,
    kPortFieldNumber = 1,
    kThrusterNumFieldNumber = 2,
  };
  // repeated .thruster.Data thrusters_ = 3;
  int thrusters__size() const;
  private:
  int _internal_thrusters__size() const;
  public:
  void clear_thrusters_();
  ::thruster::Data* mutable_thrusters_(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::thruster::Data >*
      mutable_thrusters_();
  private:
  const ::thruster::Data& _internal_thrusters_(int index) const;
  ::thruster::Data* _internal_add_thrusters_();
  public:
  const ::thruster::Data& thrusters_(int index) const;
  ::thruster::Data* add_thrusters_();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::thruster::Data >&
      thrusters_() const;

  // uint32 port = 1;
  void clear_port();
  uint32_t port() const;
  void set_port(uint32_t value);
  private:
  uint32_t _internal_port() const;
  void _internal_set_port(uint32_t value);
  public:

  // uint32 thruster_num = 2;
  void clear_thruster_num();
  uint32_t thruster_num() const;
  void set_thruster_num(uint32_t value);
  private:
  uint32_t _internal_thruster_num() const;
  void _internal_set_thruster_num(uint32_t value);
  public:

  // @@protoc_insertion_point(class_scope:thruster.OutMsg)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::thruster::Data > thrusters__;
    uint32_t port_;
    uint32_t thruster_num_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_msg_5fthruster_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// Data

// uint32 status = 1;
inline void Data::clear_status() {
  _impl_.status_ = 0u;
}
inline uint32_t Data::_internal_status() const {
  return _impl_.status_;
}
inline uint32_t Data::status() const {
  // @@protoc_insertion_point(field_get:thruster.Data.status)
  return _internal_status();
}
inline void Data::_internal_set_status(uint32_t value) {
  
  _impl_.status_ = value;
}
inline void Data::set_status(uint32_t value) {
  _internal_set_status(value);
  // @@protoc_insertion_point(field_set:thruster.Data.status)
}

// uint32 error_code = 2;
inline void Data::clear_error_code() {
  _impl_.error_code_ = 0u;
}
inline uint32_t Data::_internal_error_code() const {
  return _impl_.error_code_;
}
inline uint32_t Data::error_code() const {
  // @@protoc_insertion_point(field_get:thruster.Data.error_code)
  return _internal_error_code();
}
inline void Data::_internal_set_error_code(uint32_t value) {
  
  _impl_.error_code_ = value;
}
inline void Data::set_error_code(uint32_t value) {
  _internal_set_error_code(value);
  // @@protoc_insertion_point(field_set:thruster.Data.error_code)
}

// int32 rpm = 3;
inline void Data::clear_rpm() {
  _impl_.rpm_ = 0;
}
inline int32_t Data::_internal_rpm() const {
  return _impl_.rpm_;
}
inline int32_t Data::rpm() const {
  // @@protoc_insertion_point(field_get:thruster.Data.rpm)
  return _internal_rpm();
}
inline void Data::_internal_set_rpm(int32_t value) {
  
  _impl_.rpm_ = value;
}
inline void Data::set_rpm(int32_t value) {
  _internal_set_rpm(value);
  // @@protoc_insertion_point(field_set:thruster.Data.rpm)
}

// int32 angle = 4;
inline void Data::clear_angle() {
  _impl_.angle_ = 0;
}
inline int32_t Data::_internal_angle() const {
  return _impl_.angle_;
}
inline int32_t Data::angle() const {
  // @@protoc_insertion_point(field_get:thruster.Data.angle)
  return _internal_angle();
}
inline void Data::_internal_set_angle(int32_t value) {
  
  _impl_.angle_ = value;
}
inline void Data::set_angle(int32_t value) {
  _internal_set_angle(value);
  // @@protoc_insertion_point(field_set:thruster.Data.angle)
}

// int32 power = 5;
inline void Data::clear_power() {
  _impl_.power_ = 0;
}
inline int32_t Data::_internal_power() const {
  return _impl_.power_;
}
inline int32_t Data::power() const {
  // @@protoc_insertion_point(field_get:thruster.Data.power)
  return _internal_power();
}
inline void Data::_internal_set_power(int32_t value) {
  
  _impl_.power_ = value;
}
inline void Data::set_power(int32_t value) {
  _internal_set_power(value);
  // @@protoc_insertion_point(field_set:thruster.Data.power)
}

// uint32 bus_voltage = 6;
inline void Data::clear_bus_voltage() {
  _impl_.bus_voltage_ = 0u;
}
inline uint32_t Data::_internal_bus_voltage() const {
  return _impl_.bus_voltage_;
}
inline uint32_t Data::bus_voltage() const {
  // @@protoc_insertion_point(field_get:thruster.Data.bus_voltage)
  return _internal_bus_voltage();
}
inline void Data::_internal_set_bus_voltage(uint32_t value) {
  
  _impl_.bus_voltage_ = value;
}
inline void Data::set_bus_voltage(uint32_t value) {
  _internal_set_bus_voltage(value);
  // @@protoc_insertion_point(field_set:thruster.Data.bus_voltage)
}

// int32 bus_current = 7;
inline void Data::clear_bus_current() {
  _impl_.bus_current_ = 0;
}
inline int32_t Data::_internal_bus_current() const {
  return _impl_.bus_current_;
}
inline int32_t Data::bus_current() const {
  // @@protoc_insertion_point(field_get:thruster.Data.bus_current)
  return _internal_bus_current();
}
inline void Data::_internal_set_bus_current(int32_t value) {
  
  _impl_.bus_current_ = value;
}
inline void Data::set_bus_current(int32_t value) {
  _internal_set_bus_current(value);
  // @@protoc_insertion_point(field_set:thruster.Data.bus_current)
}

// int32 phase_current = 8;
inline void Data::clear_phase_current() {
  _impl_.phase_current_ = 0;
}
inline int32_t Data::_internal_phase_current() const {
  return _impl_.phase_current_;
}
inline int32_t Data::phase_current() const {
  // @@protoc_insertion_point(field_get:thruster.Data.phase_current)
  return _internal_phase_current();
}
inline void Data::_internal_set_phase_current(int32_t value) {
  
  _impl_.phase_current_ = value;
}
inline void Data::set_phase_current(int32_t value) {
  _internal_set_phase_current(value);
  // @@protoc_insertion_point(field_set:thruster.Data.phase_current)
}

// int32 motor_temp = 9;
inline void Data::clear_motor_temp() {
  _impl_.motor_temp_ = 0;
}
inline int32_t Data::_internal_motor_temp() const {
  return _impl_.motor_temp_;
}
inline int32_t Data::motor_temp() const {
  // @@protoc_insertion_point(field_get:thruster.Data.motor_temp)
  return _internal_motor_temp();
}
inline void Data::_internal_set_motor_temp(int32_t value) {
  
  _impl_.motor_temp_ = value;
}
inline void Data::set_motor_temp(int32_t value) {
  _internal_set_motor_temp(value);
  // @@protoc_insertion_point(field_set:thruster.Data.motor_temp)
}

// int32 mos_temp = 10;
inline void Data::clear_mos_temp() {
  _impl_.mos_temp_ = 0;
}
inline int32_t Data::_internal_mos_temp() const {
  return _impl_.mos_temp_;
}
inline int32_t Data::mos_temp() const {
  // @@protoc_insertion_point(field_get:thruster.Data.mos_temp)
  return _internal_mos_temp();
}
inline void Data::_internal_set_mos_temp(int32_t value) {
  
  _impl_.mos_temp_ = value;
}
inline void Data::set_mos_temp(int32_t value) {
  _internal_set_mos_temp(value);
  // @@protoc_insertion_point(field_set:thruster.Data.mos_temp)
}

// int32 _temp = 11;
inline void Data::clear__temp() {
  _impl_._temp_ = 0;
}
inline int32_t Data::_internal__temp() const {
  return _impl_._temp_;
}
inline int32_t Data::_temp() const {
  // @@protoc_insertion_point(field_get:thruster.Data._temp)
  return _internal__temp();
}
inline void Data::_internal_set__temp(int32_t value) {
  
  _impl_._temp_ = value;
}
inline void Data::set__temp(int32_t value) {
  _internal_set__temp(value);
  // @@protoc_insertion_point(field_set:thruster.Data._temp)
}

// uint32 run_time = 12;
inline void Data::clear_run_time() {
  _impl_.run_time_ = 0u;
}
inline uint32_t Data::_internal_run_time() const {
  return _impl_.run_time_;
}
inline uint32_t Data::run_time() const {
  // @@protoc_insertion_point(field_get:thruster.Data.run_time)
  return _internal_run_time();
}
inline void Data::_internal_set_run_time(uint32_t value) {
  
  _impl_.run_time_ = value;
}
inline void Data::set_run_time(uint32_t value) {
  _internal_set_run_time(value);
  // @@protoc_insertion_point(field_set:thruster.Data.run_time)
}

// uint32 sum_run_time = 13;
inline void Data::clear_sum_run_time() {
  _impl_.sum_run_time_ = 0u;
}
inline uint32_t Data::_internal_sum_run_time() const {
  return _impl_.sum_run_time_;
}
inline uint32_t Data::sum_run_time() const {
  // @@protoc_insertion_point(field_get:thruster.Data.sum_run_time)
  return _internal_sum_run_time();
}
inline void Data::_internal_set_sum_run_time(uint32_t value) {
  
  _impl_.sum_run_time_ = value;
}
inline void Data::set_sum_run_time(uint32_t value) {
  _internal_set_sum_run_time(value);
  // @@protoc_insertion_point(field_set:thruster.Data.sum_run_time)
}

// -------------------------------------------------------------------

// OutMsg

// uint32 port = 1;
inline void OutMsg::clear_port() {
  _impl_.port_ = 0u;
}
inline uint32_t OutMsg::_internal_port() const {
  return _impl_.port_;
}
inline uint32_t OutMsg::port() const {
  // @@protoc_insertion_point(field_get:thruster.OutMsg.port)
  return _internal_port();
}
inline void OutMsg::_internal_set_port(uint32_t value) {
  
  _impl_.port_ = value;
}
inline void OutMsg::set_port(uint32_t value) {
  _internal_set_port(value);
  // @@protoc_insertion_point(field_set:thruster.OutMsg.port)
}

// uint32 thruster_num = 2;
inline void OutMsg::clear_thruster_num() {
  _impl_.thruster_num_ = 0u;
}
inline uint32_t OutMsg::_internal_thruster_num() const {
  return _impl_.thruster_num_;
}
inline uint32_t OutMsg::thruster_num() const {
  // @@protoc_insertion_point(field_get:thruster.OutMsg.thruster_num)
  return _internal_thruster_num();
}
inline void OutMsg::_internal_set_thruster_num(uint32_t value) {
  
  _impl_.thruster_num_ = value;
}
inline void OutMsg::set_thruster_num(uint32_t value) {
  _internal_set_thruster_num(value);
  // @@protoc_insertion_point(field_set:thruster.OutMsg.thruster_num)
}

// repeated .thruster.Data thrusters_ = 3;
inline int OutMsg::_internal_thrusters__size() const {
  return _impl_.thrusters__.size();
}
inline int OutMsg::thrusters__size() const {
  return _internal_thrusters__size();
}
inline void OutMsg::clear_thrusters_() {
  _impl_.thrusters__.Clear();
}
inline ::thruster::Data* OutMsg::mutable_thrusters_(int index) {
  // @@protoc_insertion_point(field_mutable:thruster.OutMsg.thrusters_)
  return _impl_.thrusters__.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::thruster::Data >*
OutMsg::mutable_thrusters_() {
  // @@protoc_insertion_point(field_mutable_list:thruster.OutMsg.thrusters_)
  return &_impl_.thrusters__;
}
inline const ::thruster::Data& OutMsg::_internal_thrusters_(int index) const {
  return _impl_.thrusters__.Get(index);
}
inline const ::thruster::Data& OutMsg::thrusters_(int index) const {
  // @@protoc_insertion_point(field_get:thruster.OutMsg.thrusters_)
  return _internal_thrusters_(index);
}
inline ::thruster::Data* OutMsg::_internal_add_thrusters_() {
  return _impl_.thrusters__.Add();
}
inline ::thruster::Data* OutMsg::add_thrusters_() {
  ::thruster::Data* _add = _internal_add_thrusters_();
  // @@protoc_insertion_point(field_add:thruster.OutMsg.thrusters_)
  return _add;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::thruster::Data >&
OutMsg::thrusters_() const {
  // @@protoc_insertion_point(field_list:thruster.OutMsg.thrusters_)
  return _impl_.thrusters__;
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace thruster

PROTOBUF_NAMESPACE_OPEN

template <> struct is_proto_enum< ::thruster::Status> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::thruster::Status>() {
  return ::thruster::Status_descriptor();
}

PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_msg_5fthruster_2eproto
