// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: msg_gins_data.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_msg_5fgins_5fdata_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_msg_5fgins_5fdata_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_msg_5fgins_5fdata_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_msg_5fgins_5fdata_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_msg_5fgins_5fdata_2eproto;
namespace gins {
namespace data {
class GINSData;
struct GINSDataDefaultTypeInternal;
extern GINSDataDefaultTypeInternal _GINSData_default_instance_;
}  // namespace data
}  // namespace gins
PROTOBUF_NAMESPACE_OPEN
template<> ::gins::data::GINSData* Arena::CreateMaybeMessage<::gins::data::GINSData>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace gins {
namespace data {

// ===================================================================

class GINSData final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:gins.data.GINSData) */ {
 public:
  inline GINSData() : GINSData(nullptr) {}
  ~GINSData() override;
  explicit PROTOBUF_CONSTEXPR GINSData(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  GINSData(const GINSData& from);
  GINSData(GINSData&& from) noexcept
    : GINSData() {
    *this = ::std::move(from);
  }

  inline GINSData& operator=(const GINSData& from) {
    CopyFrom(from);
    return *this;
  }
  inline GINSData& operator=(GINSData&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const GINSData& default_instance() {
    return *internal_default_instance();
  }
  static inline const GINSData* internal_default_instance() {
    return reinterpret_cast<const GINSData*>(
               &_GINSData_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(GINSData& a, GINSData& b) {
    a.Swap(&b);
  }
  inline void Swap(GINSData* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(GINSData* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  GINSData* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<GINSData>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const GINSData& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const GINSData& from) {
    GINSData::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(GINSData* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "gins.data.GINSData";
  }
  protected:
  explicit GINSData(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kUtcLocalFieldNumber = 2,
    kLatitudeFieldNumber = 3,
    kPortFieldNumber = 1,
    kAltitudeFieldNumber = 5,
    kLongitudeFieldNumber = 4,
    kRollDeg10FieldNumber = 6,
    kPitchDeg10FieldNumber = 7,
    kHeadingDegFieldNumber = 8,
    kVnMps100FieldNumber = 9,
    kVeMps100FieldNumber = 10,
    kRotiFieldNumber = 11,
    kAxFieldNumber = 12,
    kAyFieldNumber = 13,
    kAazFieldNumber = 14,
    kGinsStatusFieldNumber = 15,
    kHdop10FieldNumber = 16,
    kHeadStdFieldNumber = 17,
  };
  // double utc_local = 2;
  void clear_utc_local();
  double utc_local() const;
  void set_utc_local(double value);
  private:
  double _internal_utc_local() const;
  void _internal_set_utc_local(double value);
  public:

  // double latitude = 3;
  void clear_latitude();
  double latitude() const;
  void set_latitude(double value);
  private:
  double _internal_latitude() const;
  void _internal_set_latitude(double value);
  public:

  // uint32 port = 1;
  void clear_port();
  uint32_t port() const;
  void set_port(uint32_t value);
  private:
  uint32_t _internal_port() const;
  void _internal_set_port(uint32_t value);
  public:

  // float altitude = 5;
  void clear_altitude();
  float altitude() const;
  void set_altitude(float value);
  private:
  float _internal_altitude() const;
  void _internal_set_altitude(float value);
  public:

  // double longitude = 4;
  void clear_longitude();
  double longitude() const;
  void set_longitude(double value);
  private:
  double _internal_longitude() const;
  void _internal_set_longitude(double value);
  public:

  // int32 roll_deg10 = 6;
  void clear_roll_deg10();
  int32_t roll_deg10() const;
  void set_roll_deg10(int32_t value);
  private:
  int32_t _internal_roll_deg10() const;
  void _internal_set_roll_deg10(int32_t value);
  public:

  // int32 pitch_deg10 = 7;
  void clear_pitch_deg10();
  int32_t pitch_deg10() const;
  void set_pitch_deg10(int32_t value);
  private:
  int32_t _internal_pitch_deg10() const;
  void _internal_set_pitch_deg10(int32_t value);
  public:

  // float heading_deg = 8;
  void clear_heading_deg();
  float heading_deg() const;
  void set_heading_deg(float value);
  private:
  float _internal_heading_deg() const;
  void _internal_set_heading_deg(float value);
  public:

  // int32 vn_mps100 = 9;
  void clear_vn_mps100();
  int32_t vn_mps100() const;
  void set_vn_mps100(int32_t value);
  private:
  int32_t _internal_vn_mps100() const;
  void _internal_set_vn_mps100(int32_t value);
  public:

  // int32 ve_mps100 = 10;
  void clear_ve_mps100();
  int32_t ve_mps100() const;
  void set_ve_mps100(int32_t value);
  private:
  int32_t _internal_ve_mps100() const;
  void _internal_set_ve_mps100(int32_t value);
  public:

  // float roti = 11;
  void clear_roti();
  float roti() const;
  void set_roti(float value);
  private:
  float _internal_roti() const;
  void _internal_set_roti(float value);
  public:

  // float ax = 12;
  void clear_ax();
  float ax() const;
  void set_ax(float value);
  private:
  float _internal_ax() const;
  void _internal_set_ax(float value);
  public:

  // float ay = 13;
  void clear_ay();
  float ay() const;
  void set_ay(float value);
  private:
  float _internal_ay() const;
  void _internal_set_ay(float value);
  public:

  // float aaz = 14;
  void clear_aaz();
  float aaz() const;
  void set_aaz(float value);
  private:
  float _internal_aaz() const;
  void _internal_set_aaz(float value);
  public:

  // uint32 gins_status = 15;
  void clear_gins_status();
  uint32_t gins_status() const;
  void set_gins_status(uint32_t value);
  private:
  uint32_t _internal_gins_status() const;
  void _internal_set_gins_status(uint32_t value);
  public:

  // uint32 hdop10 = 16;
  void clear_hdop10();
  uint32_t hdop10() const;
  void set_hdop10(uint32_t value);
  private:
  uint32_t _internal_hdop10() const;
  void _internal_set_hdop10(uint32_t value);
  public:

  // float head_std = 17;
  void clear_head_std();
  float head_std() const;
  void set_head_std(float value);
  private:
  float _internal_head_std() const;
  void _internal_set_head_std(float value);
  public:

  // @@protoc_insertion_point(class_scope:gins.data.GINSData)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    double utc_local_;
    double latitude_;
    uint32_t port_;
    float altitude_;
    double longitude_;
    int32_t roll_deg10_;
    int32_t pitch_deg10_;
    float heading_deg_;
    int32_t vn_mps100_;
    int32_t ve_mps100_;
    float roti_;
    float ax_;
    float ay_;
    float aaz_;
    uint32_t gins_status_;
    uint32_t hdop10_;
    float head_std_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_msg_5fgins_5fdata_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// GINSData

// uint32 port = 1;
inline void GINSData::clear_port() {
  _impl_.port_ = 0u;
}
inline uint32_t GINSData::_internal_port() const {
  return _impl_.port_;
}
inline uint32_t GINSData::port() const {
  // @@protoc_insertion_point(field_get:gins.data.GINSData.port)
  return _internal_port();
}
inline void GINSData::_internal_set_port(uint32_t value) {
  
  _impl_.port_ = value;
}
inline void GINSData::set_port(uint32_t value) {
  _internal_set_port(value);
  // @@protoc_insertion_point(field_set:gins.data.GINSData.port)
}

// double utc_local = 2;
inline void GINSData::clear_utc_local() {
  _impl_.utc_local_ = 0;
}
inline double GINSData::_internal_utc_local() const {
  return _impl_.utc_local_;
}
inline double GINSData::utc_local() const {
  // @@protoc_insertion_point(field_get:gins.data.GINSData.utc_local)
  return _internal_utc_local();
}
inline void GINSData::_internal_set_utc_local(double value) {
  
  _impl_.utc_local_ = value;
}
inline void GINSData::set_utc_local(double value) {
  _internal_set_utc_local(value);
  // @@protoc_insertion_point(field_set:gins.data.GINSData.utc_local)
}

// double latitude = 3;
inline void GINSData::clear_latitude() {
  _impl_.latitude_ = 0;
}
inline double GINSData::_internal_latitude() const {
  return _impl_.latitude_;
}
inline double GINSData::latitude() const {
  // @@protoc_insertion_point(field_get:gins.data.GINSData.latitude)
  return _internal_latitude();
}
inline void GINSData::_internal_set_latitude(double value) {
  
  _impl_.latitude_ = value;
}
inline void GINSData::set_latitude(double value) {
  _internal_set_latitude(value);
  // @@protoc_insertion_point(field_set:gins.data.GINSData.latitude)
}

// double longitude = 4;
inline void GINSData::clear_longitude() {
  _impl_.longitude_ = 0;
}
inline double GINSData::_internal_longitude() const {
  return _impl_.longitude_;
}
inline double GINSData::longitude() const {
  // @@protoc_insertion_point(field_get:gins.data.GINSData.longitude)
  return _internal_longitude();
}
inline void GINSData::_internal_set_longitude(double value) {
  
  _impl_.longitude_ = value;
}
inline void GINSData::set_longitude(double value) {
  _internal_set_longitude(value);
  // @@protoc_insertion_point(field_set:gins.data.GINSData.longitude)
}

// float altitude = 5;
inline void GINSData::clear_altitude() {
  _impl_.altitude_ = 0;
}
inline float GINSData::_internal_altitude() const {
  return _impl_.altitude_;
}
inline float GINSData::altitude() const {
  // @@protoc_insertion_point(field_get:gins.data.GINSData.altitude)
  return _internal_altitude();
}
inline void GINSData::_internal_set_altitude(float value) {
  
  _impl_.altitude_ = value;
}
inline void GINSData::set_altitude(float value) {
  _internal_set_altitude(value);
  // @@protoc_insertion_point(field_set:gins.data.GINSData.altitude)
}

// int32 roll_deg10 = 6;
inline void GINSData::clear_roll_deg10() {
  _impl_.roll_deg10_ = 0;
}
inline int32_t GINSData::_internal_roll_deg10() const {
  return _impl_.roll_deg10_;
}
inline int32_t GINSData::roll_deg10() const {
  // @@protoc_insertion_point(field_get:gins.data.GINSData.roll_deg10)
  return _internal_roll_deg10();
}
inline void GINSData::_internal_set_roll_deg10(int32_t value) {
  
  _impl_.roll_deg10_ = value;
}
inline void GINSData::set_roll_deg10(int32_t value) {
  _internal_set_roll_deg10(value);
  // @@protoc_insertion_point(field_set:gins.data.GINSData.roll_deg10)
}

// int32 pitch_deg10 = 7;
inline void GINSData::clear_pitch_deg10() {
  _impl_.pitch_deg10_ = 0;
}
inline int32_t GINSData::_internal_pitch_deg10() const {
  return _impl_.pitch_deg10_;
}
inline int32_t GINSData::pitch_deg10() const {
  // @@protoc_insertion_point(field_get:gins.data.GINSData.pitch_deg10)
  return _internal_pitch_deg10();
}
inline void GINSData::_internal_set_pitch_deg10(int32_t value) {
  
  _impl_.pitch_deg10_ = value;
}
inline void GINSData::set_pitch_deg10(int32_t value) {
  _internal_set_pitch_deg10(value);
  // @@protoc_insertion_point(field_set:gins.data.GINSData.pitch_deg10)
}

// float heading_deg = 8;
inline void GINSData::clear_heading_deg() {
  _impl_.heading_deg_ = 0;
}
inline float GINSData::_internal_heading_deg() const {
  return _impl_.heading_deg_;
}
inline float GINSData::heading_deg() const {
  // @@protoc_insertion_point(field_get:gins.data.GINSData.heading_deg)
  return _internal_heading_deg();
}
inline void GINSData::_internal_set_heading_deg(float value) {
  
  _impl_.heading_deg_ = value;
}
inline void GINSData::set_heading_deg(float value) {
  _internal_set_heading_deg(value);
  // @@protoc_insertion_point(field_set:gins.data.GINSData.heading_deg)
}

// int32 vn_mps100 = 9;
inline void GINSData::clear_vn_mps100() {
  _impl_.vn_mps100_ = 0;
}
inline int32_t GINSData::_internal_vn_mps100() const {
  return _impl_.vn_mps100_;
}
inline int32_t GINSData::vn_mps100() const {
  // @@protoc_insertion_point(field_get:gins.data.GINSData.vn_mps100)
  return _internal_vn_mps100();
}
inline void GINSData::_internal_set_vn_mps100(int32_t value) {
  
  _impl_.vn_mps100_ = value;
}
inline void GINSData::set_vn_mps100(int32_t value) {
  _internal_set_vn_mps100(value);
  // @@protoc_insertion_point(field_set:gins.data.GINSData.vn_mps100)
}

// int32 ve_mps100 = 10;
inline void GINSData::clear_ve_mps100() {
  _impl_.ve_mps100_ = 0;
}
inline int32_t GINSData::_internal_ve_mps100() const {
  return _impl_.ve_mps100_;
}
inline int32_t GINSData::ve_mps100() const {
  // @@protoc_insertion_point(field_get:gins.data.GINSData.ve_mps100)
  return _internal_ve_mps100();
}
inline void GINSData::_internal_set_ve_mps100(int32_t value) {
  
  _impl_.ve_mps100_ = value;
}
inline void GINSData::set_ve_mps100(int32_t value) {
  _internal_set_ve_mps100(value);
  // @@protoc_insertion_point(field_set:gins.data.GINSData.ve_mps100)
}

// float roti = 11;
inline void GINSData::clear_roti() {
  _impl_.roti_ = 0;
}
inline float GINSData::_internal_roti() const {
  return _impl_.roti_;
}
inline float GINSData::roti() const {
  // @@protoc_insertion_point(field_get:gins.data.GINSData.roti)
  return _internal_roti();
}
inline void GINSData::_internal_set_roti(float value) {
  
  _impl_.roti_ = value;
}
inline void GINSData::set_roti(float value) {
  _internal_set_roti(value);
  // @@protoc_insertion_point(field_set:gins.data.GINSData.roti)
}

// float ax = 12;
inline void GINSData::clear_ax() {
  _impl_.ax_ = 0;
}
inline float GINSData::_internal_ax() const {
  return _impl_.ax_;
}
inline float GINSData::ax() const {
  // @@protoc_insertion_point(field_get:gins.data.GINSData.ax)
  return _internal_ax();
}
inline void GINSData::_internal_set_ax(float value) {
  
  _impl_.ax_ = value;
}
inline void GINSData::set_ax(float value) {
  _internal_set_ax(value);
  // @@protoc_insertion_point(field_set:gins.data.GINSData.ax)
}

// float ay = 13;
inline void GINSData::clear_ay() {
  _impl_.ay_ = 0;
}
inline float GINSData::_internal_ay() const {
  return _impl_.ay_;
}
inline float GINSData::ay() const {
  // @@protoc_insertion_point(field_get:gins.data.GINSData.ay)
  return _internal_ay();
}
inline void GINSData::_internal_set_ay(float value) {
  
  _impl_.ay_ = value;
}
inline void GINSData::set_ay(float value) {
  _internal_set_ay(value);
  // @@protoc_insertion_point(field_set:gins.data.GINSData.ay)
}

// float aaz = 14;
inline void GINSData::clear_aaz() {
  _impl_.aaz_ = 0;
}
inline float GINSData::_internal_aaz() const {
  return _impl_.aaz_;
}
inline float GINSData::aaz() const {
  // @@protoc_insertion_point(field_get:gins.data.GINSData.aaz)
  return _internal_aaz();
}
inline void GINSData::_internal_set_aaz(float value) {
  
  _impl_.aaz_ = value;
}
inline void GINSData::set_aaz(float value) {
  _internal_set_aaz(value);
  // @@protoc_insertion_point(field_set:gins.data.GINSData.aaz)
}

// uint32 gins_status = 15;
inline void GINSData::clear_gins_status() {
  _impl_.gins_status_ = 0u;
}
inline uint32_t GINSData::_internal_gins_status() const {
  return _impl_.gins_status_;
}
inline uint32_t GINSData::gins_status() const {
  // @@protoc_insertion_point(field_get:gins.data.GINSData.gins_status)
  return _internal_gins_status();
}
inline void GINSData::_internal_set_gins_status(uint32_t value) {
  
  _impl_.gins_status_ = value;
}
inline void GINSData::set_gins_status(uint32_t value) {
  _internal_set_gins_status(value);
  // @@protoc_insertion_point(field_set:gins.data.GINSData.gins_status)
}

// uint32 hdop10 = 16;
inline void GINSData::clear_hdop10() {
  _impl_.hdop10_ = 0u;
}
inline uint32_t GINSData::_internal_hdop10() const {
  return _impl_.hdop10_;
}
inline uint32_t GINSData::hdop10() const {
  // @@protoc_insertion_point(field_get:gins.data.GINSData.hdop10)
  return _internal_hdop10();
}
inline void GINSData::_internal_set_hdop10(uint32_t value) {
  
  _impl_.hdop10_ = value;
}
inline void GINSData::set_hdop10(uint32_t value) {
  _internal_set_hdop10(value);
  // @@protoc_insertion_point(field_set:gins.data.GINSData.hdop10)
}

// float head_std = 17;
inline void GINSData::clear_head_std() {
  _impl_.head_std_ = 0;
}
inline float GINSData::_internal_head_std() const {
  return _impl_.head_std_;
}
inline float GINSData::head_std() const {
  // @@protoc_insertion_point(field_get:gins.data.GINSData.head_std)
  return _internal_head_std();
}
inline void GINSData::_internal_set_head_std(float value) {
  
  _impl_.head_std_ = value;
}
inline void GINSData::set_head_std(float value) {
  _internal_set_head_std(value);
  // @@protoc_insertion_point(field_set:gins.data.GINSData.head_std)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace data
}  // namespace gins

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_msg_5fgins_5fdata_2eproto
