// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: msg_thruster.proto

#include "msg_thruster.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace thruster {
PROTOBUF_CONSTEXPR Data::Data(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.status_)*/0u
  , /*decltype(_impl_.error_code_)*/0u
  , /*decltype(_impl_.rpm_)*/0
  , /*decltype(_impl_.angle_)*/0
  , /*decltype(_impl_.power_)*/0
  , /*decltype(_impl_.bus_voltage_)*/0u
  , /*decltype(_impl_.bus_current_)*/0
  , /*decltype(_impl_.phase_current_)*/0
  , /*decltype(_impl_.motor_temp_)*/0
  , /*decltype(_impl_.mos_temp_)*/0
  , /*decltype(_impl_._temp_)*/0
  , /*decltype(_impl_.run_time_)*/0u
  , /*decltype(_impl_.sum_run_time_)*/0u
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct DataDefaultTypeInternal {
  PROTOBUF_CONSTEXPR DataDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~DataDefaultTypeInternal() {}
  union {
    Data _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 DataDefaultTypeInternal _Data_default_instance_;
PROTOBUF_CONSTEXPR OutMsg::OutMsg(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.thrusters__)*/{}
  , /*decltype(_impl_.port_)*/0u
  , /*decltype(_impl_.thruster_num_)*/0u
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct OutMsgDefaultTypeInternal {
  PROTOBUF_CONSTEXPR OutMsgDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~OutMsgDefaultTypeInternal() {}
  union {
    OutMsg _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 OutMsgDefaultTypeInternal _OutMsg_default_instance_;
}  // namespace thruster
static ::_pb::Metadata file_level_metadata_msg_5fthruster_2eproto[2];
static const ::_pb::EnumDescriptor* file_level_enum_descriptors_msg_5fthruster_2eproto[1];
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_msg_5fthruster_2eproto = nullptr;

const uint32_t TableStruct_msg_5fthruster_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::thruster::Data, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::thruster::Data, _impl_.status_),
  PROTOBUF_FIELD_OFFSET(::thruster::Data, _impl_.error_code_),
  PROTOBUF_FIELD_OFFSET(::thruster::Data, _impl_.rpm_),
  PROTOBUF_FIELD_OFFSET(::thruster::Data, _impl_.angle_),
  PROTOBUF_FIELD_OFFSET(::thruster::Data, _impl_.power_),
  PROTOBUF_FIELD_OFFSET(::thruster::Data, _impl_.bus_voltage_),
  PROTOBUF_FIELD_OFFSET(::thruster::Data, _impl_.bus_current_),
  PROTOBUF_FIELD_OFFSET(::thruster::Data, _impl_.phase_current_),
  PROTOBUF_FIELD_OFFSET(::thruster::Data, _impl_.motor_temp_),
  PROTOBUF_FIELD_OFFSET(::thruster::Data, _impl_.mos_temp_),
  PROTOBUF_FIELD_OFFSET(::thruster::Data, _impl_._temp_),
  PROTOBUF_FIELD_OFFSET(::thruster::Data, _impl_.run_time_),
  PROTOBUF_FIELD_OFFSET(::thruster::Data, _impl_.sum_run_time_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::thruster::OutMsg, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::thruster::OutMsg, _impl_.port_),
  PROTOBUF_FIELD_OFFSET(::thruster::OutMsg, _impl_.thruster_num_),
  PROTOBUF_FIELD_OFFSET(::thruster::OutMsg, _impl_.thrusters__),
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::thruster::Data)},
  { 19, -1, -1, sizeof(::thruster::OutMsg)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::thruster::_Data_default_instance_._instance,
  &::thruster::_OutMsg_default_instance_._instance,
};

const char descriptor_table_protodef_msg_5fthruster_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\022msg_thruster.proto\022\010thruster\"\363\001\n\004Data\022"
  "\016\n\006status\030\001 \001(\r\022\022\n\nerror_code\030\002 \001(\r\022\013\n\003r"
  "pm\030\003 \001(\005\022\r\n\005angle\030\004 \001(\005\022\r\n\005power\030\005 \001(\005\022\023"
  "\n\013bus_voltage\030\006 \001(\r\022\023\n\013bus_current\030\007 \001(\005"
  "\022\025\n\rphase_current\030\010 \001(\005\022\022\n\nmotor_temp\030\t "
  "\001(\005\022\020\n\010mos_temp\030\n \001(\005\022\r\n\005_temp\030\013 \001(\005\022\020\n\010"
  "run_time\030\014 \001(\r\022\024\n\014sum_run_time\030\r \001(\r\"P\n\006"
  "OutMsg\022\014\n\004port\030\001 \001(\r\022\024\n\014thruster_num\030\002 \001"
  "(\r\022\"\n\nthrusters_\030\003 \003(\0132\016.thruster.Data*\372"
  "\001\n\006Status\022\n\n\006NORMAL\020\000\022\t\n\005STALL\020\001\022\022\n\016MOTO"
  "R_OVERHEAT\020\002\022\020\n\014MOS_OVERHEAT\020\004\022\020\n\014OVER_C"
  "URRENT\020\010\022\016\n\nCOMM_FAULT\020\020\022\024\n\020MOTOR_TEMP_E"
  "RROR\020 \022\022\n\016MOS_TEMP_ALARM\020@\022\021\n\014OVER_VOLTA"
  "GE\020\200\001\022\022\n\rUNDER_VOLTAGE\020\200\002\022\022\n\rCIRCUIT_FAU"
  "LT\020\200\004\022\r\n\010CHARGING\020\200\010\022\016\n\tFAN_FAULT\020\200\020\022\r\n\005"
  "OTHER\020\200\200\200\200\004B-Z+crossocean.com/edge_gatew"
  "ay/pb/mcu/thrusterb\006proto3"
  ;
static ::_pbi::once_flag descriptor_table_msg_5fthruster_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_msg_5fthruster_2eproto = {
    false, false, 666, descriptor_table_protodef_msg_5fthruster_2eproto,
    "msg_thruster.proto",
    &descriptor_table_msg_5fthruster_2eproto_once, nullptr, 0, 2,
    schemas, file_default_instances, TableStruct_msg_5fthruster_2eproto::offsets,
    file_level_metadata_msg_5fthruster_2eproto, file_level_enum_descriptors_msg_5fthruster_2eproto,
    file_level_service_descriptors_msg_5fthruster_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_msg_5fthruster_2eproto_getter() {
  return &descriptor_table_msg_5fthruster_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_msg_5fthruster_2eproto(&descriptor_table_msg_5fthruster_2eproto);
namespace thruster {
const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* Status_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_msg_5fthruster_2eproto);
  return file_level_enum_descriptors_msg_5fthruster_2eproto[0];
}
bool Status_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 4:
    case 8:
    case 16:
    case 32:
    case 64:
    case 128:
    case 256:
    case 512:
    case 1024:
    case 2048:
    case 1073741824:
      return true;
    default:
      return false;
  }
}


// ===================================================================

class Data::_Internal {
 public:
};

Data::Data(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:thruster.Data)
}
Data::Data(const Data& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  Data* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.status_){}
    , decltype(_impl_.error_code_){}
    , decltype(_impl_.rpm_){}
    , decltype(_impl_.angle_){}
    , decltype(_impl_.power_){}
    , decltype(_impl_.bus_voltage_){}
    , decltype(_impl_.bus_current_){}
    , decltype(_impl_.phase_current_){}
    , decltype(_impl_.motor_temp_){}
    , decltype(_impl_.mos_temp_){}
    , decltype(_impl_._temp_){}
    , decltype(_impl_.run_time_){}
    , decltype(_impl_.sum_run_time_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::memcpy(&_impl_.status_, &from._impl_.status_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.sum_run_time_) -
    reinterpret_cast<char*>(&_impl_.status_)) + sizeof(_impl_.sum_run_time_));
  // @@protoc_insertion_point(copy_constructor:thruster.Data)
}

inline void Data::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.status_){0u}
    , decltype(_impl_.error_code_){0u}
    , decltype(_impl_.rpm_){0}
    , decltype(_impl_.angle_){0}
    , decltype(_impl_.power_){0}
    , decltype(_impl_.bus_voltage_){0u}
    , decltype(_impl_.bus_current_){0}
    , decltype(_impl_.phase_current_){0}
    , decltype(_impl_.motor_temp_){0}
    , decltype(_impl_.mos_temp_){0}
    , decltype(_impl_._temp_){0}
    , decltype(_impl_.run_time_){0u}
    , decltype(_impl_.sum_run_time_){0u}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

Data::~Data() {
  // @@protoc_insertion_point(destructor:thruster.Data)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void Data::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
}

void Data::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void Data::Clear() {
// @@protoc_insertion_point(message_clear_start:thruster.Data)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&_impl_.status_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_impl_.sum_run_time_) -
      reinterpret_cast<char*>(&_impl_.status_)) + sizeof(_impl_.sum_run_time_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* Data::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // uint32 status = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _impl_.status_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // uint32 error_code = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 16)) {
          _impl_.error_code_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // int32 rpm = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 24)) {
          _impl_.rpm_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // int32 angle = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 32)) {
          _impl_.angle_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // int32 power = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 40)) {
          _impl_.power_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // uint32 bus_voltage = 6;
      case 6:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 48)) {
          _impl_.bus_voltage_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // int32 bus_current = 7;
      case 7:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 56)) {
          _impl_.bus_current_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // int32 phase_current = 8;
      case 8:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 64)) {
          _impl_.phase_current_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // int32 motor_temp = 9;
      case 9:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 72)) {
          _impl_.motor_temp_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // int32 mos_temp = 10;
      case 10:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 80)) {
          _impl_.mos_temp_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // int32 _temp = 11;
      case 11:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 88)) {
          _impl_._temp_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // uint32 run_time = 12;
      case 12:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 96)) {
          _impl_.run_time_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // uint32 sum_run_time = 13;
      case 13:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 104)) {
          _impl_.sum_run_time_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* Data::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:thruster.Data)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // uint32 status = 1;
  if (this->_internal_status() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(1, this->_internal_status(), target);
  }

  // uint32 error_code = 2;
  if (this->_internal_error_code() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(2, this->_internal_error_code(), target);
  }

  // int32 rpm = 3;
  if (this->_internal_rpm() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(3, this->_internal_rpm(), target);
  }

  // int32 angle = 4;
  if (this->_internal_angle() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(4, this->_internal_angle(), target);
  }

  // int32 power = 5;
  if (this->_internal_power() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(5, this->_internal_power(), target);
  }

  // uint32 bus_voltage = 6;
  if (this->_internal_bus_voltage() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(6, this->_internal_bus_voltage(), target);
  }

  // int32 bus_current = 7;
  if (this->_internal_bus_current() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(7, this->_internal_bus_current(), target);
  }

  // int32 phase_current = 8;
  if (this->_internal_phase_current() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(8, this->_internal_phase_current(), target);
  }

  // int32 motor_temp = 9;
  if (this->_internal_motor_temp() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(9, this->_internal_motor_temp(), target);
  }

  // int32 mos_temp = 10;
  if (this->_internal_mos_temp() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(10, this->_internal_mos_temp(), target);
  }

  // int32 _temp = 11;
  if (this->_internal__temp() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(11, this->_internal__temp(), target);
  }

  // uint32 run_time = 12;
  if (this->_internal_run_time() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(12, this->_internal_run_time(), target);
  }

  // uint32 sum_run_time = 13;
  if (this->_internal_sum_run_time() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(13, this->_internal_sum_run_time(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:thruster.Data)
  return target;
}

size_t Data::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:thruster.Data)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // uint32 status = 1;
  if (this->_internal_status() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(this->_internal_status());
  }

  // uint32 error_code = 2;
  if (this->_internal_error_code() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(this->_internal_error_code());
  }

  // int32 rpm = 3;
  if (this->_internal_rpm() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_rpm());
  }

  // int32 angle = 4;
  if (this->_internal_angle() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_angle());
  }

  // int32 power = 5;
  if (this->_internal_power() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_power());
  }

  // uint32 bus_voltage = 6;
  if (this->_internal_bus_voltage() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(this->_internal_bus_voltage());
  }

  // int32 bus_current = 7;
  if (this->_internal_bus_current() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_bus_current());
  }

  // int32 phase_current = 8;
  if (this->_internal_phase_current() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_phase_current());
  }

  // int32 motor_temp = 9;
  if (this->_internal_motor_temp() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_motor_temp());
  }

  // int32 mos_temp = 10;
  if (this->_internal_mos_temp() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_mos_temp());
  }

  // int32 _temp = 11;
  if (this->_internal__temp() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal__temp());
  }

  // uint32 run_time = 12;
  if (this->_internal_run_time() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(this->_internal_run_time());
  }

  // uint32 sum_run_time = 13;
  if (this->_internal_sum_run_time() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(this->_internal_sum_run_time());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData Data::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    Data::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*Data::GetClassData() const { return &_class_data_; }


void Data::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<Data*>(&to_msg);
  auto& from = static_cast<const Data&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:thruster.Data)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_status() != 0) {
    _this->_internal_set_status(from._internal_status());
  }
  if (from._internal_error_code() != 0) {
    _this->_internal_set_error_code(from._internal_error_code());
  }
  if (from._internal_rpm() != 0) {
    _this->_internal_set_rpm(from._internal_rpm());
  }
  if (from._internal_angle() != 0) {
    _this->_internal_set_angle(from._internal_angle());
  }
  if (from._internal_power() != 0) {
    _this->_internal_set_power(from._internal_power());
  }
  if (from._internal_bus_voltage() != 0) {
    _this->_internal_set_bus_voltage(from._internal_bus_voltage());
  }
  if (from._internal_bus_current() != 0) {
    _this->_internal_set_bus_current(from._internal_bus_current());
  }
  if (from._internal_phase_current() != 0) {
    _this->_internal_set_phase_current(from._internal_phase_current());
  }
  if (from._internal_motor_temp() != 0) {
    _this->_internal_set_motor_temp(from._internal_motor_temp());
  }
  if (from._internal_mos_temp() != 0) {
    _this->_internal_set_mos_temp(from._internal_mos_temp());
  }
  if (from._internal__temp() != 0) {
    _this->_internal_set__temp(from._internal__temp());
  }
  if (from._internal_run_time() != 0) {
    _this->_internal_set_run_time(from._internal_run_time());
  }
  if (from._internal_sum_run_time() != 0) {
    _this->_internal_set_sum_run_time(from._internal_sum_run_time());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void Data::CopyFrom(const Data& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:thruster.Data)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Data::IsInitialized() const {
  return true;
}

void Data::InternalSwap(Data* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(Data, _impl_.sum_run_time_)
      + sizeof(Data::_impl_.sum_run_time_)
      - PROTOBUF_FIELD_OFFSET(Data, _impl_.status_)>(
          reinterpret_cast<char*>(&_impl_.status_),
          reinterpret_cast<char*>(&other->_impl_.status_));
}

::PROTOBUF_NAMESPACE_ID::Metadata Data::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_msg_5fthruster_2eproto_getter, &descriptor_table_msg_5fthruster_2eproto_once,
      file_level_metadata_msg_5fthruster_2eproto[0]);
}

// ===================================================================

class OutMsg::_Internal {
 public:
};

OutMsg::OutMsg(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:thruster.OutMsg)
}
OutMsg::OutMsg(const OutMsg& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  OutMsg* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.thrusters__){from._impl_.thrusters__}
    , decltype(_impl_.port_){}
    , decltype(_impl_.thruster_num_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::memcpy(&_impl_.port_, &from._impl_.port_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.thruster_num_) -
    reinterpret_cast<char*>(&_impl_.port_)) + sizeof(_impl_.thruster_num_));
  // @@protoc_insertion_point(copy_constructor:thruster.OutMsg)
}

inline void OutMsg::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.thrusters__){arena}
    , decltype(_impl_.port_){0u}
    , decltype(_impl_.thruster_num_){0u}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

OutMsg::~OutMsg() {
  // @@protoc_insertion_point(destructor:thruster.OutMsg)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void OutMsg::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.thrusters__.~RepeatedPtrField();
}

void OutMsg::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void OutMsg::Clear() {
// @@protoc_insertion_point(message_clear_start:thruster.OutMsg)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.thrusters__.Clear();
  ::memset(&_impl_.port_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_impl_.thruster_num_) -
      reinterpret_cast<char*>(&_impl_.port_)) + sizeof(_impl_.thruster_num_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* OutMsg::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // uint32 port = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _impl_.port_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // uint32 thruster_num = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 16)) {
          _impl_.thruster_num_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // repeated .thruster.Data thrusters_ = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 26)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(_internal_add_thrusters_(), ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<26>(ptr));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* OutMsg::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:thruster.OutMsg)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // uint32 port = 1;
  if (this->_internal_port() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(1, this->_internal_port(), target);
  }

  // uint32 thruster_num = 2;
  if (this->_internal_thruster_num() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(2, this->_internal_thruster_num(), target);
  }

  // repeated .thruster.Data thrusters_ = 3;
  for (unsigned i = 0,
      n = static_cast<unsigned>(this->_internal_thrusters__size()); i < n; i++) {
    const auto& repfield = this->_internal_thrusters_(i);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
        InternalWriteMessage(3, repfield, repfield.GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:thruster.OutMsg)
  return target;
}

size_t OutMsg::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:thruster.OutMsg)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated .thruster.Data thrusters_ = 3;
  total_size += 1UL * this->_internal_thrusters__size();
  for (const auto& msg : this->_impl_.thrusters__) {
    total_size +=
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(msg);
  }

  // uint32 port = 1;
  if (this->_internal_port() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(this->_internal_port());
  }

  // uint32 thruster_num = 2;
  if (this->_internal_thruster_num() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(this->_internal_thruster_num());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData OutMsg::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    OutMsg::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*OutMsg::GetClassData() const { return &_class_data_; }


void OutMsg::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<OutMsg*>(&to_msg);
  auto& from = static_cast<const OutMsg&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:thruster.OutMsg)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_impl_.thrusters__.MergeFrom(from._impl_.thrusters__);
  if (from._internal_port() != 0) {
    _this->_internal_set_port(from._internal_port());
  }
  if (from._internal_thruster_num() != 0) {
    _this->_internal_set_thruster_num(from._internal_thruster_num());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void OutMsg::CopyFrom(const OutMsg& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:thruster.OutMsg)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool OutMsg::IsInitialized() const {
  return true;
}

void OutMsg::InternalSwap(OutMsg* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.thrusters__.InternalSwap(&other->_impl_.thrusters__);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(OutMsg, _impl_.thruster_num_)
      + sizeof(OutMsg::_impl_.thruster_num_)
      - PROTOBUF_FIELD_OFFSET(OutMsg, _impl_.port_)>(
          reinterpret_cast<char*>(&_impl_.port_),
          reinterpret_cast<char*>(&other->_impl_.port_));
}

::PROTOBUF_NAMESPACE_ID::Metadata OutMsg::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_msg_5fthruster_2eproto_getter, &descriptor_table_msg_5fthruster_2eproto_once,
      file_level_metadata_msg_5fthruster_2eproto[1]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace thruster
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::thruster::Data*
Arena::CreateMaybeMessage< ::thruster::Data >(Arena* arena) {
  return Arena::CreateMessageInternal< ::thruster::Data >(arena);
}
template<> PROTOBUF_NOINLINE ::thruster::OutMsg*
Arena::CreateMaybeMessage< ::thruster::OutMsg >(Arena* arena) {
  return Arena::CreateMessageInternal< ::thruster::OutMsg >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
