// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: msg_gins_data.proto

#include "msg_gins_data.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace gins {
namespace data {
PROTOBUF_CONSTEXPR GINSData::GINSData(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.utc_local_)*/0
  , /*decltype(_impl_.latitude_)*/0
  , /*decltype(_impl_.port_)*/0u
  , /*decltype(_impl_.altitude_)*/0
  , /*decltype(_impl_.longitude_)*/0
  , /*decltype(_impl_.roll_deg10_)*/0
  , /*decltype(_impl_.pitch_deg10_)*/0
  , /*decltype(_impl_.heading_deg_)*/0
  , /*decltype(_impl_.vn_mps100_)*/0
  , /*decltype(_impl_.ve_mps100_)*/0
  , /*decltype(_impl_.roti_)*/0
  , /*decltype(_impl_.ax_)*/0
  , /*decltype(_impl_.ay_)*/0
  , /*decltype(_impl_.aaz_)*/0
  , /*decltype(_impl_.gins_status_)*/0u
  , /*decltype(_impl_.hdop10_)*/0u
  , /*decltype(_impl_.head_std_)*/0
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct GINSDataDefaultTypeInternal {
  PROTOBUF_CONSTEXPR GINSDataDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~GINSDataDefaultTypeInternal() {}
  union {
    GINSData _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 GINSDataDefaultTypeInternal _GINSData_default_instance_;
}  // namespace data
}  // namespace gins
static ::_pb::Metadata file_level_metadata_msg_5fgins_5fdata_2eproto[1];
static constexpr ::_pb::EnumDescriptor const** file_level_enum_descriptors_msg_5fgins_5fdata_2eproto = nullptr;
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_msg_5fgins_5fdata_2eproto = nullptr;

const uint32_t TableStruct_msg_5fgins_5fdata_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::gins::data::GINSData, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_d
  PROTOBUF_FIELD_OFFSET(::gins::data::GINSData, _impl_.port_),//端口号
  PROTOBUF_FIELD_OFFSET(::gins::data::GINSData, _impl_.utc_local_),//UTC本地时间
  PROTOBUF_FIELD_OFFSET(::gins::data::GINSData, _impl_.latitude_),//纬度
  PROTOBUF_FIELD_OFFSET(::gins::data::GINSData, _impl_.longitude_),//经度
  PROTOBUF_FIELD_OFFSET(::gins::data::GINSData, _impl_.altitude_),//高度
  PROTOBUF_FIELD_OFFSET(::gins::data::GINSData, _impl_.roll_deg10_),//横滚角
  PROTOBUF_FIELD_OFFSET(::gins::data::GINSData, _impl_.pitch_deg10_),//俯仰角
  PROTOBUF_FIELD_OFFSET(::gins::data::GINSData, _impl_.heading_deg_),//航向角
  PROTOBUF_FIELD_OFFSET(::gins::data::GINSData, _impl_.vn_mps100_),//北向速度
  PROTOBUF_FIELD_OFFSET(::gins::data::GINSData, _impl_.ve_mps100_),//东向速度
  PROTOBUF_FIELD_OFFSET(::gins::data::GINSData, _impl_.roti_),//转向角速度
  PROTOBUF_FIELD_OFFSET(::gins::data::GINSData, _impl_.ax_),//X轴加速度
  PROTOBUF_FIELD_OFFSET(::gins::data::GINSData, _impl_.ay_),//Y轴加速度
  PROTOBUF_FIELD_OFFSET(::gins::data::GINSData, _impl_.aaz_),//A轴加速度（Z）
  PROTOBUF_FIELD_OFFSET(::gins::data::GINSData, _impl_.gins_status_),//GINS状态码
  PROTOBUF_FIELD_OFFSET(::gins::data::GINSData, _impl_.hdop10_),//水平精度因子HDOP
  PROTOBUF_FIELD_OFFSET(::gins::data::GINSData, _impl_.head_std_),//航向标准
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::gins::data::GINSData)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::gins::data::_GINSData_default_instance_._instance,
};

const char descriptor_table_protodef_msg_5fgins_5fdata_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\023msg_gins_data.proto\022\tgins.data\"\260\002\n\010GIN"
  "SData\022\014\n\004port\030\001 \001(\r\022\021\n\tutc_local\030\002 \001(\001\022\020"
  "\n\010latitude\030\003 \001(\001\022\021\n\tlongitude\030\004 \001(\001\022\020\n\010a"
  "ltitude\030\005 \001(\002\022\022\n\nroll_deg10\030\006 \001(\005\022\023\n\013pit"
  "ch_deg10\030\007 \001(\005\022\023\n\013heading_deg\030\010 \001(\002\022\021\n\tv"
  "n_mps100\030\t \001(\005\022\021\n\tve_mps100\030\n \001(\005\022\014\n\004rot"
  "i\030\013 \001(\002\022\n\n\002ax\030\014 \001(\002\022\n\n\002ay\030\r \001(\002\022\013\n\003aaz\030\016"
  " \001(\002\022\023\n\013gins_status\030\017 \001(\r\022\016\n\006hdop10\030\020 \001("
  "\r\022\020\n\010head_std\030\021 \001(\002B.Z,crossocean.com/ed"
  "ge_gateway/pb/mcu/gins_datab\006proto3"
  ;
static ::_pbi::once_flag descriptor_table_msg_5fgins_5fdata_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_msg_5fgins_5fdata_2eproto = {
    false, false, 395, descriptor_table_protodef_msg_5fgins_5fdata_2eproto,
    "msg_gins_data.proto",
    &descriptor_table_msg_5fgins_5fdata_2eproto_once, nullptr, 0, 1,
    schemas, file_default_instances, TableStruct_msg_5fgins_5fdata_2eproto::offsets,
    file_level_metadata_msg_5fgins_5fdata_2eproto, file_level_enum_descriptors_msg_5fgins_5fdata_2eproto,
    file_level_service_descriptors_msg_5fgins_5fdata_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_msg_5fgins_5fdata_2eproto_getter() {
  return &descriptor_table_msg_5fgins_5fdata_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_msg_5fgins_5fdata_2eproto(&descriptor_table_msg_5fgins_5fdata_2eproto);
namespace gins {
namespace data {

// ===================================================================

class GINSData::_Internal {
 public:
};

GINSData::GINSData(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:gins.data.GINSData)
}
GINSData::GINSData(const GINSData& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  GINSData* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.utc_local_){}
    , decltype(_impl_.latitude_){}
    , decltype(_impl_.port_){}
    , decltype(_impl_.altitude_){}
    , decltype(_impl_.longitude_){}
    , decltype(_impl_.roll_deg10_){}
    , decltype(_impl_.pitch_deg10_){}
    , decltype(_impl_.heading_deg_){}
    , decltype(_impl_.vn_mps100_){}
    , decltype(_impl_.ve_mps100_){}
    , decltype(_impl_.roti_){}
    , decltype(_impl_.ax_){}
    , decltype(_impl_.ay_){}
    , decltype(_impl_.aaz_){}
    , decltype(_impl_.gins_status_){}
    , decltype(_impl_.hdop10_){}
    , decltype(_impl_.head_std_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::memcpy(&_impl_.utc_local_, &from._impl_.utc_local_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.head_std_) -
    reinterpret_cast<char*>(&_impl_.utc_local_)) + sizeof(_impl_.head_std_));
  // @@protoc_insertion_point(copy_constructor:gins.data.GINSData)
}

inline void GINSData::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.utc_local_){0}
    , decltype(_impl_.latitude_){0}
    , decltype(_impl_.port_){0u}
    , decltype(_impl_.altitude_){0}
    , decltype(_impl_.longitude_){0}
    , decltype(_impl_.roll_deg10_){0}
    , decltype(_impl_.pitch_deg10_){0}
    , decltype(_impl_.heading_deg_){0}
    , decltype(_impl_.vn_mps100_){0}
    , decltype(_impl_.ve_mps100_){0}
    , decltype(_impl_.roti_){0}
    , decltype(_impl_.ax_){0}
    , decltype(_impl_.ay_){0}
    , decltype(_impl_.aaz_){0}
    , decltype(_impl_.gins_status_){0u}
    , decltype(_impl_.hdop10_){0u}
    , decltype(_impl_.head_std_){0}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

GINSData::~GINSData() {
  // @@protoc_insertion_point(destructor:gins.data.GINSData)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void GINSData::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
}

void GINSData::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void GINSData::Clear() {
// @@protoc_insertion_point(message_clear_start:gins.data.GINSData)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&_impl_.utc_local_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_impl_.head_std_) -
      reinterpret_cast<char*>(&_impl_.utc_local_)) + sizeof(_impl_.head_std_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* GINSData::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // uint32 port = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _impl_.port_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // double utc_local = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 17)) {
          _impl_.utc_local_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr);
          ptr += sizeof(double);
        } else
          goto handle_unusual;
        continue;
      // double latitude = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 25)) {
          _impl_.latitude_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr);
          ptr += sizeof(double);
        } else
          goto handle_unusual;
        continue;
      // double longitude = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 33)) {
          _impl_.longitude_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr);
          ptr += sizeof(double);
        } else
          goto handle_unusual;
        continue;
      // float altitude = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 45)) {
          _impl_.altitude_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr);
          ptr += sizeof(float);
        } else
          goto handle_unusual;
        continue;
      // int32 roll_deg10 = 6;
      case 6:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 48)) {
          _impl_.roll_deg10_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // int32 pitch_deg10 = 7;
      case 7:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 56)) {
          _impl_.pitch_deg10_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // float heading_deg = 8;
      case 8:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 69)) {
          _impl_.heading_deg_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr);
          ptr += sizeof(float);
        } else
          goto handle_unusual;
        continue;
      // int32 vn_mps100 = 9;
      case 9:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 72)) {
          _impl_.vn_mps100_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // int32 ve_mps100 = 10;
      case 10:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 80)) {
          _impl_.ve_mps100_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // float roti = 11;
      case 11:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 93)) {
          _impl_.roti_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr);
          ptr += sizeof(float);
        } else
          goto handle_unusual;
        continue;
      // float ax = 12;
      case 12:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 101)) {
          _impl_.ax_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr);
          ptr += sizeof(float);
        } else
          goto handle_unusual;
        continue;
      // float ay = 13;
      case 13:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 109)) {
          _impl_.ay_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr);
          ptr += sizeof(float);
        } else
          goto handle_unusual;
        continue;
      // float aaz = 14;
      case 14:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 117)) {
          _impl_.aaz_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr);
          ptr += sizeof(float);
        } else
          goto handle_unusual;
        continue;
      // uint32 gins_status = 15;
      case 15:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 120)) {
          _impl_.gins_status_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // uint32 hdop10 = 16;
      case 16:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 128)) {
          _impl_.hdop10_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // float head_std = 17;
      case 17:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 141)) {
          _impl_.head_std_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr);
          ptr += sizeof(float);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* GINSData::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:gins.data.GINSData)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // uint32 port = 1;
  if (this->_internal_port() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(1, this->_internal_port(), target);
  }

  // double utc_local = 2;
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_utc_local = this->_internal_utc_local();
  uint64_t raw_utc_local;
  memcpy(&raw_utc_local, &tmp_utc_local, sizeof(tmp_utc_local));
  if (raw_utc_local != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteDoubleToArray(2, this->_internal_utc_local(), target);
  }

  // double latitude = 3;
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_latitude = this->_internal_latitude();
  uint64_t raw_latitude;
  memcpy(&raw_latitude, &tmp_latitude, sizeof(tmp_latitude));
  if (raw_latitude != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteDoubleToArray(3, this->_internal_latitude(), target);
  }

  // double longitude = 4;
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_longitude = this->_internal_longitude();
  uint64_t raw_longitude;
  memcpy(&raw_longitude, &tmp_longitude, sizeof(tmp_longitude));
  if (raw_longitude != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteDoubleToArray(4, this->_internal_longitude(), target);
  }

  // float altitude = 5;
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_altitude = this->_internal_altitude();
  uint32_t raw_altitude;
  memcpy(&raw_altitude, &tmp_altitude, sizeof(tmp_altitude));
  if (raw_altitude != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteFloatToArray(5, this->_internal_altitude(), target);
  }

  // int32 roll_deg10 = 6;
  if (this->_internal_roll_deg10() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(6, this->_internal_roll_deg10(), target);
  }

  // int32 pitch_deg10 = 7;
  if (this->_internal_pitch_deg10() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(7, this->_internal_pitch_deg10(), target);
  }

  // float heading_deg = 8;
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_heading_deg = this->_internal_heading_deg();
  uint32_t raw_heading_deg;
  memcpy(&raw_heading_deg, &tmp_heading_deg, sizeof(tmp_heading_deg));
  if (raw_heading_deg != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteFloatToArray(8, this->_internal_heading_deg(), target);
  }

  // int32 vn_mps100 = 9;
  if (this->_internal_vn_mps100() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(9, this->_internal_vn_mps100(), target);
  }

  // int32 ve_mps100 = 10;
  if (this->_internal_ve_mps100() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(10, this->_internal_ve_mps100(), target);
  }

  // float roti = 11;
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_roti = this->_internal_roti();
  uint32_t raw_roti;
  memcpy(&raw_roti, &tmp_roti, sizeof(tmp_roti));
  if (raw_roti != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteFloatToArray(11, this->_internal_roti(), target);
  }

  // float ax = 12;
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_ax = this->_internal_ax();
  uint32_t raw_ax;
  memcpy(&raw_ax, &tmp_ax, sizeof(tmp_ax));
  if (raw_ax != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteFloatToArray(12, this->_internal_ax(), target);
  }

  // float ay = 13;
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_ay = this->_internal_ay();
  uint32_t raw_ay;
  memcpy(&raw_ay, &tmp_ay, sizeof(tmp_ay));
  if (raw_ay != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteFloatToArray(13, this->_internal_ay(), target);
  }

  // float aaz = 14;
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_aaz = this->_internal_aaz();
  uint32_t raw_aaz;
  memcpy(&raw_aaz, &tmp_aaz, sizeof(tmp_aaz));
  if (raw_aaz != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteFloatToArray(14, this->_internal_aaz(), target);
  }

  // uint32 gins_status = 15;
  if (this->_internal_gins_status() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(15, this->_internal_gins_status(), target);
  }

  // uint32 hdop10 = 16;
  if (this->_internal_hdop10() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(16, this->_internal_hdop10(), target);
  }

  // float head_std = 17;
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_head_std = this->_internal_head_std();
  uint32_t raw_head_std;
  memcpy(&raw_head_std, &tmp_head_std, sizeof(tmp_head_std));
  if (raw_head_std != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteFloatToArray(17, this->_internal_head_std(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:gins.data.GINSData)
  return target;
}

size_t GINSData::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:gins.data.GINSData)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // double utc_local = 2;
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_utc_local = this->_internal_utc_local();
  uint64_t raw_utc_local;
  memcpy(&raw_utc_local, &tmp_utc_local, sizeof(tmp_utc_local));
  if (raw_utc_local != 0) {
    total_size += 1 + 8;
  }

  // double latitude = 3;
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_latitude = this->_internal_latitude();
  uint64_t raw_latitude;
  memcpy(&raw_latitude, &tmp_latitude, sizeof(tmp_latitude));
  if (raw_latitude != 0) {
    total_size += 1 + 8;
  }

  // uint32 port = 1;
  if (this->_internal_port() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(this->_internal_port());
  }

  // float altitude = 5;
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_altitude = this->_internal_altitude();
  uint32_t raw_altitude;
  memcpy(&raw_altitude, &tmp_altitude, sizeof(tmp_altitude));
  if (raw_altitude != 0) {
    total_size += 1 + 4;
  }

  // double longitude = 4;
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_longitude = this->_internal_longitude();
  uint64_t raw_longitude;
  memcpy(&raw_longitude, &tmp_longitude, sizeof(tmp_longitude));
  if (raw_longitude != 0) {
    total_size += 1 + 8;
  }

  // int32 roll_deg10 = 6;
  if (this->_internal_roll_deg10() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_roll_deg10());
  }

  // int32 pitch_deg10 = 7;
  if (this->_internal_pitch_deg10() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_pitch_deg10());
  }

  // float heading_deg = 8;
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_heading_deg = this->_internal_heading_deg();
  uint32_t raw_heading_deg;
  memcpy(&raw_heading_deg, &tmp_heading_deg, sizeof(tmp_heading_deg));
  if (raw_heading_deg != 0) {
    total_size += 1 + 4;
  }

  // int32 vn_mps100 = 9;
  if (this->_internal_vn_mps100() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_vn_mps100());
  }

  // int32 ve_mps100 = 10;
  if (this->_internal_ve_mps100() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_ve_mps100());
  }

  // float roti = 11;
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_roti = this->_internal_roti();
  uint32_t raw_roti;
  memcpy(&raw_roti, &tmp_roti, sizeof(tmp_roti));
  if (raw_roti != 0) {
    total_size += 1 + 4;
  }

  // float ax = 12;
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_ax = this->_internal_ax();
  uint32_t raw_ax;
  memcpy(&raw_ax, &tmp_ax, sizeof(tmp_ax));
  if (raw_ax != 0) {
    total_size += 1 + 4;
  }

  // float ay = 13;
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_ay = this->_internal_ay();
  uint32_t raw_ay;
  memcpy(&raw_ay, &tmp_ay, sizeof(tmp_ay));
  if (raw_ay != 0) {
    total_size += 1 + 4;
  }

  // float aaz = 14;
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_aaz = this->_internal_aaz();
  uint32_t raw_aaz;
  memcpy(&raw_aaz, &tmp_aaz, sizeof(tmp_aaz));
  if (raw_aaz != 0) {
    total_size += 1 + 4;
  }

  // uint32 gins_status = 15;
  if (this->_internal_gins_status() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(this->_internal_gins_status());
  }

  // uint32 hdop10 = 16;
  if (this->_internal_hdop10() != 0) {
    total_size += 2 +
      ::_pbi::WireFormatLite::UInt32Size(
        this->_internal_hdop10());
  }

  // float head_std = 17;
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_head_std = this->_internal_head_std();
  uint32_t raw_head_std;
  memcpy(&raw_head_std, &tmp_head_std, sizeof(tmp_head_std));
  if (raw_head_std != 0) {
    total_size += 2 + 4;
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData GINSData::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    GINSData::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GINSData::GetClassData() const { return &_class_data_; }


void GINSData::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<GINSData*>(&to_msg);
  auto& from = static_cast<const GINSData&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:gins.data.GINSData)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_utc_local = from._internal_utc_local();
  uint64_t raw_utc_local;
  memcpy(&raw_utc_local, &tmp_utc_local, sizeof(tmp_utc_local));
  if (raw_utc_local != 0) {
    _this->_internal_set_utc_local(from._internal_utc_local());
  }
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_latitude = from._internal_latitude();
  uint64_t raw_latitude;
  memcpy(&raw_latitude, &tmp_latitude, sizeof(tmp_latitude));
  if (raw_latitude != 0) {
    _this->_internal_set_latitude(from._internal_latitude());
  }
  if (from._internal_port() != 0) {
    _this->_internal_set_port(from._internal_port());
  }
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_altitude = from._internal_altitude();
  uint32_t raw_altitude;
  memcpy(&raw_altitude, &tmp_altitude, sizeof(tmp_altitude));
  if (raw_altitude != 0) {
    _this->_internal_set_altitude(from._internal_altitude());
  }
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_longitude = from._internal_longitude();
  uint64_t raw_longitude;
  memcpy(&raw_longitude, &tmp_longitude, sizeof(tmp_longitude));
  if (raw_longitude != 0) {
    _this->_internal_set_longitude(from._internal_longitude());
  }
  if (from._internal_roll_deg10() != 0) {
    _this->_internal_set_roll_deg10(from._internal_roll_deg10());
  }
  if (from._internal_pitch_deg10() != 0) {
    _this->_internal_set_pitch_deg10(from._internal_pitch_deg10());
  }
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_heading_deg = from._internal_heading_deg();
  uint32_t raw_heading_deg;
  memcpy(&raw_heading_deg, &tmp_heading_deg, sizeof(tmp_heading_deg));
  if (raw_heading_deg != 0) {
    _this->_internal_set_heading_deg(from._internal_heading_deg());
  }
  if (from._internal_vn_mps100() != 0) {
    _this->_internal_set_vn_mps100(from._internal_vn_mps100());
  }
  if (from._internal_ve_mps100() != 0) {
    _this->_internal_set_ve_mps100(from._internal_ve_mps100());
  }
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_roti = from._internal_roti();
  uint32_t raw_roti;
  memcpy(&raw_roti, &tmp_roti, sizeof(tmp_roti));
  if (raw_roti != 0) {
    _this->_internal_set_roti(from._internal_roti());
  }
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_ax = from._internal_ax();
  uint32_t raw_ax;
  memcpy(&raw_ax, &tmp_ax, sizeof(tmp_ax));
  if (raw_ax != 0) {
    _this->_internal_set_ax(from._internal_ax());
  }
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_ay = from._internal_ay();
  uint32_t raw_ay;
  memcpy(&raw_ay, &tmp_ay, sizeof(tmp_ay));
  if (raw_ay != 0) {
    _this->_internal_set_ay(from._internal_ay());
  }
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_aaz = from._internal_aaz();
  uint32_t raw_aaz;
  memcpy(&raw_aaz, &tmp_aaz, sizeof(tmp_aaz));
  if (raw_aaz != 0) {
    _this->_internal_set_aaz(from._internal_aaz());
  }
  if (from._internal_gins_status() != 0) {
    _this->_internal_set_gins_status(from._internal_gins_status());
  }
  if (from._internal_hdop10() != 0) {
    _this->_internal_set_hdop10(from._internal_hdop10());
  }
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_head_std = from._internal_head_std();
  uint32_t raw_head_std;
  memcpy(&raw_head_std, &tmp_head_std, sizeof(tmp_head_std));
  if (raw_head_std != 0) {
    _this->_internal_set_head_std(from._internal_head_std());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void GINSData::CopyFrom(const GINSData& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:gins.data.GINSData)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool GINSData::IsInitialized() const {
  return true;
}

void GINSData::InternalSwap(GINSData* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(GINSData, _impl_.head_std_)
      + sizeof(GINSData::_impl_.head_std_)
      - PROTOBUF_FIELD_OFFSET(GINSData, _impl_.utc_local_)>(
          reinterpret_cast<char*>(&_impl_.utc_local_),
          reinterpret_cast<char*>(&other->_impl_.utc_local_));
}

::PROTOBUF_NAMESPACE_ID::Metadata GINSData::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_msg_5fgins_5fdata_2eproto_getter, &descriptor_table_msg_5fgins_5fdata_2eproto_once,
      file_level_metadata_msg_5fgins_5fdata_2eproto[0]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace data
}  // namespace gins
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::gins::data::GINSData*
Arena::CreateMaybeMessage< ::gins::data::GINSData >(Arena* arena) {
  return Arena::CreateMessageInternal< ::gins::data::GINSData >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
