// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: msg_battery.proto

#include "msg_battery.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace battery {
PROTOBUF_CONSTEXPR DCDCData::DCDCData(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.status_)*/0u
  , /*decltype(_impl_.bus_voltage_)*/0u
  , /*decltype(_impl_.out_current_)*/0
  , /*decltype(_impl_.out_power_)*/0
  , /*decltype(_impl_.temp_)*/0
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct DCDCDataDefaultTypeInternal {
  PROTOBUF_CONSTEXPR DCDCDataDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~DCDCDataDefaultTypeInternal() {}
  union {
    DCDCData _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 DCDCDataDefaultTypeInternal _DCDCData_default_instance_;
PROTOBUF_CONSTEXPR PCSData::PCSData(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.status_)*/0u
  , /*decltype(_impl_.out_voltage_)*/0u
  , /*decltype(_impl_.out_current_)*/0
  , /*decltype(_impl_.out_power_)*/0
  , /*decltype(_impl_.temp_)*/0
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct PCSDataDefaultTypeInternal {
  PROTOBUF_CONSTEXPR PCSDataDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~PCSDataDefaultTypeInternal() {}
  union {
    PCSData _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 PCSDataDefaultTypeInternal _PCSData_default_instance_;
PROTOBUF_CONSTEXPR OutBatteryMsg::OutBatteryMsg(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.batteries_)*/{}
  , /*decltype(_impl_.dcdc_list_)*/{}
  , /*decltype(_impl_.pcs_list_)*/{}
  , /*decltype(_impl_.port_)*/0u
  , /*decltype(_impl_.battery_num_)*/0u
  , /*decltype(_impl_.pack_voltage_)*/0u
  , /*decltype(_impl_.pack_current_)*/0
  , /*decltype(_impl_.pack_rsoc_)*/0u
  , /*decltype(_impl_.pack_alarm_)*/false
  , /*decltype(_impl_.dcdc_num_)*/0u
  , /*decltype(_impl_.pcs_num_)*/0u
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct OutBatteryMsgDefaultTypeInternal {
  PROTOBUF_CONSTEXPR OutBatteryMsgDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~OutBatteryMsgDefaultTypeInternal() {}
  union {
    OutBatteryMsg _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 OutBatteryMsgDefaultTypeInternal _OutBatteryMsg_default_instance_;
PROTOBUF_CONSTEXPR BatteryMsg::BatteryMsg(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.cell_voltages_)*/{}
  , /*decltype(_impl_._cell_voltages_cached_byte_size_)*/{0}
  , /*decltype(_impl_.ntc_temps_)*/{}
  , /*decltype(_impl_._ntc_temps_cached_byte_size_)*/{0}
  , /*decltype(_impl_.error_code_)*/uint64_t{0u}
  , /*decltype(_impl_.data_status_)*/0
  , /*decltype(_impl_.rsoc_)*/0u
  , /*decltype(_impl_.voltage_)*/0u
  , /*decltype(_impl_.current_)*/0
  , /*decltype(_impl_.residual_capacity_)*/0u
  , /*decltype(_impl_.nominal_capacity_)*/0u
  , /*decltype(_impl_.cycle_count_)*/0u
  , /*decltype(_impl_.cell_series_count_)*/0u
  , /*decltype(_impl_.ntc_num_)*/0u
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct BatteryMsgDefaultTypeInternal {
  PROTOBUF_CONSTEXPR BatteryMsgDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~BatteryMsgDefaultTypeInternal() {}
  union {
    BatteryMsg _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 BatteryMsgDefaultTypeInternal _BatteryMsg_default_instance_;
}  // namespace battery
static ::_pb::Metadata file_level_metadata_msg_5fbattery_2eproto[4];
static const ::_pb::EnumDescriptor* file_level_enum_descriptors_msg_5fbattery_2eproto[2];
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_msg_5fbattery_2eproto = nullptr;

const uint32_t TableStruct_msg_5fbattery_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::battery::DCDCData, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::battery::DCDCData, _impl_.status_),
  PROTOBUF_FIELD_OFFSET(::battery::DCDCData, _impl_.bus_voltage_),
  PROTOBUF_FIELD_OFFSET(::battery::DCDCData, _impl_.out_current_),
  PROTOBUF_FIELD_OFFSET(::battery::DCDCData, _impl_.out_power_),
  PROTOBUF_FIELD_OFFSET(::battery::DCDCData, _impl_.temp_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::battery::PCSData, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::battery::PCSData, _impl_.status_),
  PROTOBUF_FIELD_OFFSET(::battery::PCSData, _impl_.out_voltage_),
  PROTOBUF_FIELD_OFFSET(::battery::PCSData, _impl_.out_current_),
  PROTOBUF_FIELD_OFFSET(::battery::PCSData, _impl_.out_power_),
  PROTOBUF_FIELD_OFFSET(::battery::PCSData, _impl_.temp_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::battery::OutBatteryMsg, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::battery::OutBatteryMsg, _impl_.port_),
  PROTOBUF_FIELD_OFFSET(::battery::OutBatteryMsg, _impl_.battery_num_),
  PROTOBUF_FIELD_OFFSET(::battery::OutBatteryMsg, _impl_.batteries_),
  PROTOBUF_FIELD_OFFSET(::battery::OutBatteryMsg, _impl_.pack_voltage_),
  PROTOBUF_FIELD_OFFSET(::battery::OutBatteryMsg, _impl_.pack_current_),
  PROTOBUF_FIELD_OFFSET(::battery::OutBatteryMsg, _impl_.pack_rsoc_),
  PROTOBUF_FIELD_OFFSET(::battery::OutBatteryMsg, _impl_.pack_alarm_),
  PROTOBUF_FIELD_OFFSET(::battery::OutBatteryMsg, _impl_.dcdc_num_),
  PROTOBUF_FIELD_OFFSET(::battery::OutBatteryMsg, _impl_.dcdc_list_),
  PROTOBUF_FIELD_OFFSET(::battery::OutBatteryMsg, _impl_.pcs_num_),
  PROTOBUF_FIELD_OFFSET(::battery::OutBatteryMsg, _impl_.pcs_list_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::battery::BatteryMsg, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::battery::BatteryMsg, _impl_.data_status_),
  PROTOBUF_FIELD_OFFSET(::battery::BatteryMsg, _impl_.error_code_),
  PROTOBUF_FIELD_OFFSET(::battery::BatteryMsg, _impl_.rsoc_),
  PROTOBUF_FIELD_OFFSET(::battery::BatteryMsg, _impl_.voltage_),
  PROTOBUF_FIELD_OFFSET(::battery::BatteryMsg, _impl_.current_),
  PROTOBUF_FIELD_OFFSET(::battery::BatteryMsg, _impl_.residual_capacity_),
  PROTOBUF_FIELD_OFFSET(::battery::BatteryMsg, _impl_.nominal_capacity_),
  PROTOBUF_FIELD_OFFSET(::battery::BatteryMsg, _impl_.cycle_count_),
  PROTOBUF_FIELD_OFFSET(::battery::BatteryMsg, _impl_.cell_series_count_),
  PROTOBUF_FIELD_OFFSET(::battery::BatteryMsg, _impl_.cell_voltages_),
  PROTOBUF_FIELD_OFFSET(::battery::BatteryMsg, _impl_.ntc_num_),
  PROTOBUF_FIELD_OFFSET(::battery::BatteryMsg, _impl_.ntc_temps_),
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::battery::DCDCData)},
  { 11, -1, -1, sizeof(::battery::PCSData)},
  { 22, -1, -1, sizeof(::battery::OutBatteryMsg)},
  { 39, -1, -1, sizeof(::battery::BatteryMsg)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::battery::_DCDCData_default_instance_._instance,
  &::battery::_PCSData_default_instance_._instance,
  &::battery::_OutBatteryMsg_default_instance_._instance,
  &::battery::_BatteryMsg_default_instance_._instance,
};

const char descriptor_table_protodef_msg_5fbattery_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\021msg_battery.proto\022\007battery\"e\n\010DCDCData"
  "\022\016\n\006status\030\001 \001(\r\022\023\n\013bus_voltage\030\002 \001(\r\022\023\n"
  "\013out_current\030\003 \001(\005\022\021\n\tout_power\030\004 \001(\005\022\014\n"
  "\004temp\030\005 \001(\005\"d\n\007PCSData\022\016\n\006status\030\001 \001(\r\022\023"
  "\n\013out_voltage\030\002 \001(\r\022\023\n\013out_current\030\003 \001(\005"
  "\022\021\n\tout_power\030\004 \001(\005\022\014\n\004temp\030\005 \001(\005\"\232\002\n\rOu"
  "tBatteryMsg\022\014\n\004port\030\001 \001(\r\022\023\n\013battery_num"
  "\030\002 \001(\r\022&\n\tbatteries\030\003 \003(\0132\023.battery.Batt"
  "eryMsg\022\024\n\014pack_voltage\030\004 \001(\r\022\024\n\014pack_cur"
  "rent\030\005 \001(\005\022\021\n\tpack_rsoc\030\006 \001(\r\022\022\n\npack_al"
  "arm\030\007 \001(\010\022\020\n\010dcdc_num\030\010 \001(\r\022$\n\tdcdc_list"
  "\030\t \003(\0132\021.battery.DCDCData\022\017\n\007pcs_num\030\n \001"
  "(\r\022\"\n\010pcs_list\030\013 \003(\0132\020.battery.PCSData\"\232"
  "\002\n\nBatteryMsg\022(\n\013data_status\030\001 \001(\0162\023.bat"
  "tery.DataStatus\022\022\n\nerror_code\030\002 \001(\004\022\014\n\004r"
  "soc\030\003 \001(\r\022\017\n\007voltage\030\004 \001(\r\022\017\n\007current\030\005 "
  "\001(\005\022\031\n\021residual_capacity\030\006 \001(\r\022\030\n\020nomina"
  "l_capacity\030\007 \001(\r\022\023\n\013cycle_count\030\010 \001(\r\022\031\n"
  "\021cell_series_count\030\t \001(\r\022\025\n\rcell_voltage"
  "s\030\n \003(\r\022\017\n\007ntc_num\030\013 \001(\r\022\021\n\tntc_temps\030\014 "
  "\003(\005*\231\001\n\nDataStatus\022\016\n\nALL_NORMAL\020\000\022\013\n\007TI"
  "MEOUT\020\001\022\r\n\tCRC_ERROR\020\002\022\021\n\rINVALID_PARAM\020"
  "\003\022\014\n\010NOT_INIT\020\004\022\014\n\010HW_FAULT\020\005\022\r\n\tBUS_ERR"
  "OR\020\006\022\017\n\013NO_RESPONSE\020\007\022\020\n\013OTHER_ERROR\020\377\001*"
  "\327\002\n\020BatteryErrorCode\022\014\n\010NO_ERROR\020\000\022\025\n\021CE"
  "LL_OVER_VOLTAGE\020\001\022\026\n\022CELL_UNDER_VOLTAGE\020"
  "\002\022\025\n\021PACK_OVER_VOLTAGE\020\004\022\026\n\022PACK_UNDER_V"
  "OLTAGE\020\010\022\024\n\020CHARGE_OVER_TEMP\020\020\022\023\n\017CHARGE"
  "_LOW_TEMP\020 \022\027\n\023DISCHARGE_OVER_TEMP\020@\022\027\n\022"
  "DISCHARGE_LOW_TEMP\020\200\001\022\030\n\023CHARGE_OVER_CUR"
  "RENT\020\200\002\022\033\n\026DISCHARGE_OVER_CURRENT\020\200\004\022\022\n\r"
  "SHORT_CIRCUIT\020\200\010\022\027\n\022FRONT_END_IC_ERROR\020\200"
  "\020\022\026\n\021SOFTWARE_LOCK_MOS\020\200 B,Z*crossocean."
  "com/edge_gateway/pb/mcu/batteryb\006proto3"
  ;
static ::_pbi::once_flag descriptor_table_msg_5fbattery_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_msg_5fbattery_2eproto = {
    false, false, 1359, descriptor_table_protodef_msg_5fbattery_2eproto,
    "msg_battery.proto",
    &descriptor_table_msg_5fbattery_2eproto_once, nullptr, 0, 4,
    schemas, file_default_instances, TableStruct_msg_5fbattery_2eproto::offsets,
    file_level_metadata_msg_5fbattery_2eproto, file_level_enum_descriptors_msg_5fbattery_2eproto,
    file_level_service_descriptors_msg_5fbattery_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_msg_5fbattery_2eproto_getter() {
  return &descriptor_table_msg_5fbattery_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_msg_5fbattery_2eproto(&descriptor_table_msg_5fbattery_2eproto);
namespace battery {
const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* DataStatus_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_msg_5fbattery_2eproto);
  return file_level_enum_descriptors_msg_5fbattery_2eproto[0];
}
bool DataStatus_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
    case 4:
    case 5:
    case 6:
    case 7:
    case 255:
      return true;
    default:
      return false;
  }
}

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* BatteryErrorCode_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_msg_5fbattery_2eproto);
  return file_level_enum_descriptors_msg_5fbattery_2eproto[1];
}
bool BatteryErrorCode_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 4:
    case 8:
    case 16:
    case 32:
    case 64:
    case 128:
    case 256:
    case 512:
    case 1024:
    case 2048:
    case 4096:
      return true;
    default:
      return false;
  }
}


// ===================================================================

class DCDCData::_Internal {
 public:
};

DCDCData::DCDCData(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:battery.DCDCData)
}
DCDCData::DCDCData(const DCDCData& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  DCDCData* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.status_){}
    , decltype(_impl_.bus_voltage_){}
    , decltype(_impl_.out_current_){}
    , decltype(_impl_.out_power_){}
    , decltype(_impl_.temp_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::memcpy(&_impl_.status_, &from._impl_.status_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.temp_) -
    reinterpret_cast<char*>(&_impl_.status_)) + sizeof(_impl_.temp_));
  // @@protoc_insertion_point(copy_constructor:battery.DCDCData)
}

inline void DCDCData::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.status_){0u}
    , decltype(_impl_.bus_voltage_){0u}
    , decltype(_impl_.out_current_){0}
    , decltype(_impl_.out_power_){0}
    , decltype(_impl_.temp_){0}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

DCDCData::~DCDCData() {
  // @@protoc_insertion_point(destructor:battery.DCDCData)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void DCDCData::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
}

void DCDCData::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void DCDCData::Clear() {
// @@protoc_insertion_point(message_clear_start:battery.DCDCData)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&_impl_.status_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_impl_.temp_) -
      reinterpret_cast<char*>(&_impl_.status_)) + sizeof(_impl_.temp_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* DCDCData::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // uint32 status = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _impl_.status_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // uint32 bus_voltage = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 16)) {
          _impl_.bus_voltage_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // int32 out_current = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 24)) {
          _impl_.out_current_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // int32 out_power = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 32)) {
          _impl_.out_power_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // int32 temp = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 40)) {
          _impl_.temp_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* DCDCData::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:battery.DCDCData)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // uint32 status = 1;
  if (this->_internal_status() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(1, this->_internal_status(), target);
  }

  // uint32 bus_voltage = 2;
  if (this->_internal_bus_voltage() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(2, this->_internal_bus_voltage(), target);
  }

  // int32 out_current = 3;
  if (this->_internal_out_current() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(3, this->_internal_out_current(), target);
  }

  // int32 out_power = 4;
  if (this->_internal_out_power() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(4, this->_internal_out_power(), target);
  }

  // int32 temp = 5;
  if (this->_internal_temp() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(5, this->_internal_temp(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:battery.DCDCData)
  return target;
}

size_t DCDCData::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:battery.DCDCData)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // uint32 status = 1;
  if (this->_internal_status() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(this->_internal_status());
  }

  // uint32 bus_voltage = 2;
  if (this->_internal_bus_voltage() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(this->_internal_bus_voltage());
  }

  // int32 out_current = 3;
  if (this->_internal_out_current() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_out_current());
  }

  // int32 out_power = 4;
  if (this->_internal_out_power() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_out_power());
  }

  // int32 temp = 5;
  if (this->_internal_temp() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_temp());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData DCDCData::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    DCDCData::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*DCDCData::GetClassData() const { return &_class_data_; }


void DCDCData::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<DCDCData*>(&to_msg);
  auto& from = static_cast<const DCDCData&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:battery.DCDCData)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_status() != 0) {
    _this->_internal_set_status(from._internal_status());
  }
  if (from._internal_bus_voltage() != 0) {
    _this->_internal_set_bus_voltage(from._internal_bus_voltage());
  }
  if (from._internal_out_current() != 0) {
    _this->_internal_set_out_current(from._internal_out_current());
  }
  if (from._internal_out_power() != 0) {
    _this->_internal_set_out_power(from._internal_out_power());
  }
  if (from._internal_temp() != 0) {
    _this->_internal_set_temp(from._internal_temp());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void DCDCData::CopyFrom(const DCDCData& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:battery.DCDCData)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool DCDCData::IsInitialized() const {
  return true;
}

void DCDCData::InternalSwap(DCDCData* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(DCDCData, _impl_.temp_)
      + sizeof(DCDCData::_impl_.temp_)
      - PROTOBUF_FIELD_OFFSET(DCDCData, _impl_.status_)>(
          reinterpret_cast<char*>(&_impl_.status_),
          reinterpret_cast<char*>(&other->_impl_.status_));
}

::PROTOBUF_NAMESPACE_ID::Metadata DCDCData::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_msg_5fbattery_2eproto_getter, &descriptor_table_msg_5fbattery_2eproto_once,
      file_level_metadata_msg_5fbattery_2eproto[0]);
}

// ===================================================================

class PCSData::_Internal {
 public:
};

PCSData::PCSData(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:battery.PCSData)
}
PCSData::PCSData(const PCSData& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  PCSData* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.status_){}
    , decltype(_impl_.out_voltage_){}
    , decltype(_impl_.out_current_){}
    , decltype(_impl_.out_power_){}
    , decltype(_impl_.temp_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::memcpy(&_impl_.status_, &from._impl_.status_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.temp_) -
    reinterpret_cast<char*>(&_impl_.status_)) + sizeof(_impl_.temp_));
  // @@protoc_insertion_point(copy_constructor:battery.PCSData)
}

inline void PCSData::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.status_){0u}
    , decltype(_impl_.out_voltage_){0u}
    , decltype(_impl_.out_current_){0}
    , decltype(_impl_.out_power_){0}
    , decltype(_impl_.temp_){0}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

PCSData::~PCSData() {
  // @@protoc_insertion_point(destructor:battery.PCSData)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void PCSData::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
}

void PCSData::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void PCSData::Clear() {
// @@protoc_insertion_point(message_clear_start:battery.PCSData)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&_impl_.status_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_impl_.temp_) -
      reinterpret_cast<char*>(&_impl_.status_)) + sizeof(_impl_.temp_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* PCSData::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // uint32 status = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _impl_.status_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // uint32 out_voltage = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 16)) {
          _impl_.out_voltage_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // int32 out_current = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 24)) {
          _impl_.out_current_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // int32 out_power = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 32)) {
          _impl_.out_power_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // int32 temp = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 40)) {
          _impl_.temp_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* PCSData::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:battery.PCSData)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // uint32 status = 1;
  if (this->_internal_status() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(1, this->_internal_status(), target);
  }

  // uint32 out_voltage = 2;
  if (this->_internal_out_voltage() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(2, this->_internal_out_voltage(), target);
  }

  // int32 out_current = 3;
  if (this->_internal_out_current() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(3, this->_internal_out_current(), target);
  }

  // int32 out_power = 4;
  if (this->_internal_out_power() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(4, this->_internal_out_power(), target);
  }

  // int32 temp = 5;
  if (this->_internal_temp() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(5, this->_internal_temp(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:battery.PCSData)
  return target;
}

size_t PCSData::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:battery.PCSData)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // uint32 status = 1;
  if (this->_internal_status() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(this->_internal_status());
  }

  // uint32 out_voltage = 2;
  if (this->_internal_out_voltage() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(this->_internal_out_voltage());
  }

  // int32 out_current = 3;
  if (this->_internal_out_current() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_out_current());
  }

  // int32 out_power = 4;
  if (this->_internal_out_power() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_out_power());
  }

  // int32 temp = 5;
  if (this->_internal_temp() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_temp());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData PCSData::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    PCSData::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*PCSData::GetClassData() const { return &_class_data_; }


void PCSData::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<PCSData*>(&to_msg);
  auto& from = static_cast<const PCSData&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:battery.PCSData)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_status() != 0) {
    _this->_internal_set_status(from._internal_status());
  }
  if (from._internal_out_voltage() != 0) {
    _this->_internal_set_out_voltage(from._internal_out_voltage());
  }
  if (from._internal_out_current() != 0) {
    _this->_internal_set_out_current(from._internal_out_current());
  }
  if (from._internal_out_power() != 0) {
    _this->_internal_set_out_power(from._internal_out_power());
  }
  if (from._internal_temp() != 0) {
    _this->_internal_set_temp(from._internal_temp());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void PCSData::CopyFrom(const PCSData& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:battery.PCSData)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool PCSData::IsInitialized() const {
  return true;
}

void PCSData::InternalSwap(PCSData* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(PCSData, _impl_.temp_)
      + sizeof(PCSData::_impl_.temp_)
      - PROTOBUF_FIELD_OFFSET(PCSData, _impl_.status_)>(
          reinterpret_cast<char*>(&_impl_.status_),
          reinterpret_cast<char*>(&other->_impl_.status_));
}

::PROTOBUF_NAMESPACE_ID::Metadata PCSData::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_msg_5fbattery_2eproto_getter, &descriptor_table_msg_5fbattery_2eproto_once,
      file_level_metadata_msg_5fbattery_2eproto[1]);
}

// ===================================================================

class OutBatteryMsg::_Internal {
 public:
};

OutBatteryMsg::OutBatteryMsg(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:battery.OutBatteryMsg)
}
OutBatteryMsg::OutBatteryMsg(const OutBatteryMsg& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  OutBatteryMsg* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.batteries_){from._impl_.batteries_}
    , decltype(_impl_.dcdc_list_){from._impl_.dcdc_list_}
    , decltype(_impl_.pcs_list_){from._impl_.pcs_list_}
    , decltype(_impl_.port_){}
    , decltype(_impl_.battery_num_){}
    , decltype(_impl_.pack_voltage_){}
    , decltype(_impl_.pack_current_){}
    , decltype(_impl_.pack_rsoc_){}
    , decltype(_impl_.pack_alarm_){}
    , decltype(_impl_.dcdc_num_){}
    , decltype(_impl_.pcs_num_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::memcpy(&_impl_.port_, &from._impl_.port_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.pcs_num_) -
    reinterpret_cast<char*>(&_impl_.port_)) + sizeof(_impl_.pcs_num_));
  // @@protoc_insertion_point(copy_constructor:battery.OutBatteryMsg)
}

inline void OutBatteryMsg::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.batteries_){arena}
    , decltype(_impl_.dcdc_list_){arena}
    , decltype(_impl_.pcs_list_){arena}
    , decltype(_impl_.port_){0u}
    , decltype(_impl_.battery_num_){0u}
    , decltype(_impl_.pack_voltage_){0u}
    , decltype(_impl_.pack_current_){0}
    , decltype(_impl_.pack_rsoc_){0u}
    , decltype(_impl_.pack_alarm_){false}
    , decltype(_impl_.dcdc_num_){0u}
    , decltype(_impl_.pcs_num_){0u}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

OutBatteryMsg::~OutBatteryMsg() {
  // @@protoc_insertion_point(destructor:battery.OutBatteryMsg)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void OutBatteryMsg::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.batteries_.~RepeatedPtrField();
  _impl_.dcdc_list_.~RepeatedPtrField();
  _impl_.pcs_list_.~RepeatedPtrField();
}

void OutBatteryMsg::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void OutBatteryMsg::Clear() {
// @@protoc_insertion_point(message_clear_start:battery.OutBatteryMsg)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.batteries_.Clear();
  _impl_.dcdc_list_.Clear();
  _impl_.pcs_list_.Clear();
  ::memset(&_impl_.port_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_impl_.pcs_num_) -
      reinterpret_cast<char*>(&_impl_.port_)) + sizeof(_impl_.pcs_num_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* OutBatteryMsg::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // uint32 port = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _impl_.port_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // uint32 battery_num = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 16)) {
          _impl_.battery_num_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // repeated .battery.BatteryMsg batteries = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 26)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(_internal_add_batteries(), ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<26>(ptr));
        } else
          goto handle_unusual;
        continue;
      // uint32 pack_voltage = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 32)) {
          _impl_.pack_voltage_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // int32 pack_current = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 40)) {
          _impl_.pack_current_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // uint32 pack_rsoc = 6;
      case 6:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 48)) {
          _impl_.pack_rsoc_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // bool pack_alarm = 7;
      case 7:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 56)) {
          _impl_.pack_alarm_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // uint32 dcdc_num = 8;
      case 8:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 64)) {
          _impl_.dcdc_num_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // repeated .battery.DCDCData dcdc_list = 9;
      case 9:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 74)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(_internal_add_dcdc_list(), ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<74>(ptr));
        } else
          goto handle_unusual;
        continue;
      // uint32 pcs_num = 10;
      case 10:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 80)) {
          _impl_.pcs_num_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // repeated .battery.PCSData pcs_list = 11;
      case 11:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 90)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(_internal_add_pcs_list(), ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<90>(ptr));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* OutBatteryMsg::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:battery.OutBatteryMsg)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // uint32 port = 1;
  if (this->_internal_port() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(1, this->_internal_port(), target);
  }

  // uint32 battery_num = 2;
  if (this->_internal_battery_num() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(2, this->_internal_battery_num(), target);
  }

  // repeated .battery.BatteryMsg batteries = 3;
  for (unsigned i = 0,
      n = static_cast<unsigned>(this->_internal_batteries_size()); i < n; i++) {
    const auto& repfield = this->_internal_batteries(i);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
        InternalWriteMessage(3, repfield, repfield.GetCachedSize(), target, stream);
  }

  // uint32 pack_voltage = 4;
  if (this->_internal_pack_voltage() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(4, this->_internal_pack_voltage(), target);
  }

  // int32 pack_current = 5;
  if (this->_internal_pack_current() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(5, this->_internal_pack_current(), target);
  }

  // uint32 pack_rsoc = 6;
  if (this->_internal_pack_rsoc() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(6, this->_internal_pack_rsoc(), target);
  }

  // bool pack_alarm = 7;
  if (this->_internal_pack_alarm() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteBoolToArray(7, this->_internal_pack_alarm(), target);
  }

  // uint32 dcdc_num = 8;
  if (this->_internal_dcdc_num() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(8, this->_internal_dcdc_num(), target);
  }

  // repeated .battery.DCDCData dcdc_list = 9;
  for (unsigned i = 0,
      n = static_cast<unsigned>(this->_internal_dcdc_list_size()); i < n; i++) {
    const auto& repfield = this->_internal_dcdc_list(i);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
        InternalWriteMessage(9, repfield, repfield.GetCachedSize(), target, stream);
  }

  // uint32 pcs_num = 10;
  if (this->_internal_pcs_num() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(10, this->_internal_pcs_num(), target);
  }

  // repeated .battery.PCSData pcs_list = 11;
  for (unsigned i = 0,
      n = static_cast<unsigned>(this->_internal_pcs_list_size()); i < n; i++) {
    const auto& repfield = this->_internal_pcs_list(i);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
        InternalWriteMessage(11, repfield, repfield.GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:battery.OutBatteryMsg)
  return target;
}

size_t OutBatteryMsg::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:battery.OutBatteryMsg)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated .battery.BatteryMsg batteries = 3;
  total_size += 1UL * this->_internal_batteries_size();
  for (const auto& msg : this->_impl_.batteries_) {
    total_size +=
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(msg);
  }

  // repeated .battery.DCDCData dcdc_list = 9;
  total_size += 1UL * this->_internal_dcdc_list_size();
  for (const auto& msg : this->_impl_.dcdc_list_) {
    total_size +=
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(msg);
  }

  // repeated .battery.PCSData pcs_list = 11;
  total_size += 1UL * this->_internal_pcs_list_size();
  for (const auto& msg : this->_impl_.pcs_list_) {
    total_size +=
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(msg);
  }

  // uint32 port = 1;
  if (this->_internal_port() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(this->_internal_port());
  }

  // uint32 battery_num = 2;
  if (this->_internal_battery_num() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(this->_internal_battery_num());
  }

  // uint32 pack_voltage = 4;
  if (this->_internal_pack_voltage() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(this->_internal_pack_voltage());
  }

  // int32 pack_current = 5;
  if (this->_internal_pack_current() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_pack_current());
  }

  // uint32 pack_rsoc = 6;
  if (this->_internal_pack_rsoc() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(this->_internal_pack_rsoc());
  }

  // bool pack_alarm = 7;
  if (this->_internal_pack_alarm() != 0) {
    total_size += 1 + 1;
  }

  // uint32 dcdc_num = 8;
  if (this->_internal_dcdc_num() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(this->_internal_dcdc_num());
  }

  // uint32 pcs_num = 10;
  if (this->_internal_pcs_num() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(this->_internal_pcs_num());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData OutBatteryMsg::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    OutBatteryMsg::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*OutBatteryMsg::GetClassData() const { return &_class_data_; }


void OutBatteryMsg::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<OutBatteryMsg*>(&to_msg);
  auto& from = static_cast<const OutBatteryMsg&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:battery.OutBatteryMsg)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_impl_.batteries_.MergeFrom(from._impl_.batteries_);
  _this->_impl_.dcdc_list_.MergeFrom(from._impl_.dcdc_list_);
  _this->_impl_.pcs_list_.MergeFrom(from._impl_.pcs_list_);
  if (from._internal_port() != 0) {
    _this->_internal_set_port(from._internal_port());
  }
  if (from._internal_battery_num() != 0) {
    _this->_internal_set_battery_num(from._internal_battery_num());
  }
  if (from._internal_pack_voltage() != 0) {
    _this->_internal_set_pack_voltage(from._internal_pack_voltage());
  }
  if (from._internal_pack_current() != 0) {
    _this->_internal_set_pack_current(from._internal_pack_current());
  }
  if (from._internal_pack_rsoc() != 0) {
    _this->_internal_set_pack_rsoc(from._internal_pack_rsoc());
  }
  if (from._internal_pack_alarm() != 0) {
    _this->_internal_set_pack_alarm(from._internal_pack_alarm());
  }
  if (from._internal_dcdc_num() != 0) {
    _this->_internal_set_dcdc_num(from._internal_dcdc_num());
  }
  if (from._internal_pcs_num() != 0) {
    _this->_internal_set_pcs_num(from._internal_pcs_num());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void OutBatteryMsg::CopyFrom(const OutBatteryMsg& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:battery.OutBatteryMsg)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool OutBatteryMsg::IsInitialized() const {
  return true;
}

void OutBatteryMsg::InternalSwap(OutBatteryMsg* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.batteries_.InternalSwap(&other->_impl_.batteries_);
  _impl_.dcdc_list_.InternalSwap(&other->_impl_.dcdc_list_);
  _impl_.pcs_list_.InternalSwap(&other->_impl_.pcs_list_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(OutBatteryMsg, _impl_.pcs_num_)
      + sizeof(OutBatteryMsg::_impl_.pcs_num_)
      - PROTOBUF_FIELD_OFFSET(OutBatteryMsg, _impl_.port_)>(
          reinterpret_cast<char*>(&_impl_.port_),
          reinterpret_cast<char*>(&other->_impl_.port_));
}

::PROTOBUF_NAMESPACE_ID::Metadata OutBatteryMsg::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_msg_5fbattery_2eproto_getter, &descriptor_table_msg_5fbattery_2eproto_once,
      file_level_metadata_msg_5fbattery_2eproto[2]);
}

// ===================================================================

class BatteryMsg::_Internal {
 public:
};

BatteryMsg::BatteryMsg(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:battery.BatteryMsg)
}
BatteryMsg::BatteryMsg(const BatteryMsg& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  BatteryMsg* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.cell_voltages_){from._impl_.cell_voltages_}
    , /*decltype(_impl_._cell_voltages_cached_byte_size_)*/{0}
    , decltype(_impl_.ntc_temps_){from._impl_.ntc_temps_}
    , /*decltype(_impl_._ntc_temps_cached_byte_size_)*/{0}
    , decltype(_impl_.error_code_){}
    , decltype(_impl_.data_status_){}
    , decltype(_impl_.rsoc_){}
    , decltype(_impl_.voltage_){}
    , decltype(_impl_.current_){}
    , decltype(_impl_.residual_capacity_){}
    , decltype(_impl_.nominal_capacity_){}
    , decltype(_impl_.cycle_count_){}
    , decltype(_impl_.cell_series_count_){}
    , decltype(_impl_.ntc_num_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::memcpy(&_impl_.error_code_, &from._impl_.error_code_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.ntc_num_) -
    reinterpret_cast<char*>(&_impl_.error_code_)) + sizeof(_impl_.ntc_num_));
  // @@protoc_insertion_point(copy_constructor:battery.BatteryMsg)
}

inline void BatteryMsg::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.cell_voltages_){arena}
    , /*decltype(_impl_._cell_voltages_cached_byte_size_)*/{0}
    , decltype(_impl_.ntc_temps_){arena}
    , /*decltype(_impl_._ntc_temps_cached_byte_size_)*/{0}
    , decltype(_impl_.error_code_){uint64_t{0u}}
    , decltype(_impl_.data_status_){0}
    , decltype(_impl_.rsoc_){0u}
    , decltype(_impl_.voltage_){0u}
    , decltype(_impl_.current_){0}
    , decltype(_impl_.residual_capacity_){0u}
    , decltype(_impl_.nominal_capacity_){0u}
    , decltype(_impl_.cycle_count_){0u}
    , decltype(_impl_.cell_series_count_){0u}
    , decltype(_impl_.ntc_num_){0u}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

BatteryMsg::~BatteryMsg() {
  // @@protoc_insertion_point(destructor:battery.BatteryMsg)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void BatteryMsg::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.cell_voltages_.~RepeatedField();
  _impl_.ntc_temps_.~RepeatedField();
}

void BatteryMsg::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void BatteryMsg::Clear() {
// @@protoc_insertion_point(message_clear_start:battery.BatteryMsg)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.cell_voltages_.Clear();
  _impl_.ntc_temps_.Clear();
  ::memset(&_impl_.error_code_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_impl_.ntc_num_) -
      reinterpret_cast<char*>(&_impl_.error_code_)) + sizeof(_impl_.ntc_num_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* BatteryMsg::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // .battery.DataStatus data_status = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          uint64_t val = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
          _internal_set_data_status(static_cast<::battery::DataStatus>(val));
        } else
          goto handle_unusual;
        continue;
      // uint64 error_code = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 16)) {
          _impl_.error_code_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // uint32 rsoc = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 24)) {
          _impl_.rsoc_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // uint32 voltage = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 32)) {
          _impl_.voltage_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // int32 current = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 40)) {
          _impl_.current_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // uint32 residual_capacity = 6;
      case 6:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 48)) {
          _impl_.residual_capacity_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // uint32 nominal_capacity = 7;
      case 7:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 56)) {
          _impl_.nominal_capacity_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // uint32 cycle_count = 8;
      case 8:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 64)) {
          _impl_.cycle_count_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // uint32 cell_series_count = 9;
      case 9:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 72)) {
          _impl_.cell_series_count_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // repeated uint32 cell_voltages = 10;
      case 10:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 82)) {
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::PackedUInt32Parser(_internal_mutable_cell_voltages(), ptr, ctx);
          CHK_(ptr);
        } else if (static_cast<uint8_t>(tag) == 80) {
          _internal_add_cell_voltages(::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr));
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // uint32 ntc_num = 11;
      case 11:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 88)) {
          _impl_.ntc_num_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // repeated int32 ntc_temps = 12;
      case 12:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 98)) {
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::PackedInt32Parser(_internal_mutable_ntc_temps(), ptr, ctx);
          CHK_(ptr);
        } else if (static_cast<uint8_t>(tag) == 96) {
          _internal_add_ntc_temps(::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr));
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* BatteryMsg::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:battery.BatteryMsg)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // .battery.DataStatus data_status = 1;
  if (this->_internal_data_status() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteEnumToArray(
      1, this->_internal_data_status(), target);
  }

  // uint64 error_code = 2;
  if (this->_internal_error_code() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt64ToArray(2, this->_internal_error_code(), target);
  }

  // uint32 rsoc = 3;
  if (this->_internal_rsoc() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(3, this->_internal_rsoc(), target);
  }

  // uint32 voltage = 4;
  if (this->_internal_voltage() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(4, this->_internal_voltage(), target);
  }

  // int32 current = 5;
  if (this->_internal_current() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(5, this->_internal_current(), target);
  }

  // uint32 residual_capacity = 6;
  if (this->_internal_residual_capacity() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(6, this->_internal_residual_capacity(), target);
  }

  // uint32 nominal_capacity = 7;
  if (this->_internal_nominal_capacity() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(7, this->_internal_nominal_capacity(), target);
  }

  // uint32 cycle_count = 8;
  if (this->_internal_cycle_count() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(8, this->_internal_cycle_count(), target);
  }

  // uint32 cell_series_count = 9;
  if (this->_internal_cell_series_count() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(9, this->_internal_cell_series_count(), target);
  }

  // repeated uint32 cell_voltages = 10;
  {
    int byte_size = _impl_._cell_voltages_cached_byte_size_.load(std::memory_order_relaxed);
    if (byte_size > 0) {
      target = stream->WriteUInt32Packed(
          10, _internal_cell_voltages(), byte_size, target);
    }
  }

  // uint32 ntc_num = 11;
  if (this->_internal_ntc_num() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(11, this->_internal_ntc_num(), target);
  }

  // repeated int32 ntc_temps = 12;
  {
    int byte_size = _impl_._ntc_temps_cached_byte_size_.load(std::memory_order_relaxed);
    if (byte_size > 0) {
      target = stream->WriteInt32Packed(
          12, _internal_ntc_temps(), byte_size, target);
    }
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:battery.BatteryMsg)
  return target;
}

size_t BatteryMsg::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:battery.BatteryMsg)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated uint32 cell_voltages = 10;
  {
    size_t data_size = ::_pbi::WireFormatLite::
      UInt32Size(this->_impl_.cell_voltages_);
    if (data_size > 0) {
      total_size += 1 +
        ::_pbi::WireFormatLite::Int32Size(static_cast<int32_t>(data_size));
    }
    int cached_size = ::_pbi::ToCachedSize(data_size);
    _impl_._cell_voltages_cached_byte_size_.store(cached_size,
                                    std::memory_order_relaxed);
    total_size += data_size;
  }

  // repeated int32 ntc_temps = 12;
  {
    size_t data_size = ::_pbi::WireFormatLite::
      Int32Size(this->_impl_.ntc_temps_);
    if (data_size > 0) {
      total_size += 1 +
        ::_pbi::WireFormatLite::Int32Size(static_cast<int32_t>(data_size));
    }
    int cached_size = ::_pbi::ToCachedSize(data_size);
    _impl_._ntc_temps_cached_byte_size_.store(cached_size,
                                    std::memory_order_relaxed);
    total_size += data_size;
  }

  // uint64 error_code = 2;
  if (this->_internal_error_code() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(this->_internal_error_code());
  }

  // .battery.DataStatus data_status = 1;
  if (this->_internal_data_status() != 0) {
    total_size += 1 +
      ::_pbi::WireFormatLite::EnumSize(this->_internal_data_status());
  }

  // uint32 rsoc = 3;
  if (this->_internal_rsoc() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(this->_internal_rsoc());
  }

  // uint32 voltage = 4;
  if (this->_internal_voltage() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(this->_internal_voltage());
  }

  // int32 current = 5;
  if (this->_internal_current() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_current());
  }

  // uint32 residual_capacity = 6;
  if (this->_internal_residual_capacity() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(this->_internal_residual_capacity());
  }

  // uint32 nominal_capacity = 7;
  if (this->_internal_nominal_capacity() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(this->_internal_nominal_capacity());
  }

  // uint32 cycle_count = 8;
  if (this->_internal_cycle_count() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(this->_internal_cycle_count());
  }

  // uint32 cell_series_count = 9;
  if (this->_internal_cell_series_count() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(this->_internal_cell_series_count());
  }

  // uint32 ntc_num = 11;
  if (this->_internal_ntc_num() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(this->_internal_ntc_num());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData BatteryMsg::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    BatteryMsg::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*BatteryMsg::GetClassData() const { return &_class_data_; }


void BatteryMsg::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<BatteryMsg*>(&to_msg);
  auto& from = static_cast<const BatteryMsg&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:battery.BatteryMsg)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_impl_.cell_voltages_.MergeFrom(from._impl_.cell_voltages_);
  _this->_impl_.ntc_temps_.MergeFrom(from._impl_.ntc_temps_);
  if (from._internal_error_code() != 0) {
    _this->_internal_set_error_code(from._internal_error_code());
  }
  if (from._internal_data_status() != 0) {
    _this->_internal_set_data_status(from._internal_data_status());
  }
  if (from._internal_rsoc() != 0) {
    _this->_internal_set_rsoc(from._internal_rsoc());
  }
  if (from._internal_voltage() != 0) {
    _this->_internal_set_voltage(from._internal_voltage());
  }
  if (from._internal_current() != 0) {
    _this->_internal_set_current(from._internal_current());
  }
  if (from._internal_residual_capacity() != 0) {
    _this->_internal_set_residual_capacity(from._internal_residual_capacity());
  }
  if (from._internal_nominal_capacity() != 0) {
    _this->_internal_set_nominal_capacity(from._internal_nominal_capacity());
  }
  if (from._internal_cycle_count() != 0) {
    _this->_internal_set_cycle_count(from._internal_cycle_count());
  }
  if (from._internal_cell_series_count() != 0) {
    _this->_internal_set_cell_series_count(from._internal_cell_series_count());
  }
  if (from._internal_ntc_num() != 0) {
    _this->_internal_set_ntc_num(from._internal_ntc_num());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void BatteryMsg::CopyFrom(const BatteryMsg& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:battery.BatteryMsg)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool BatteryMsg::IsInitialized() const {
  return true;
}

void BatteryMsg::InternalSwap(BatteryMsg* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.cell_voltages_.InternalSwap(&other->_impl_.cell_voltages_);
  _impl_.ntc_temps_.InternalSwap(&other->_impl_.ntc_temps_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(BatteryMsg, _impl_.ntc_num_)
      + sizeof(BatteryMsg::_impl_.ntc_num_)
      - PROTOBUF_FIELD_OFFSET(BatteryMsg, _impl_.error_code_)>(
          reinterpret_cast<char*>(&_impl_.error_code_),
          reinterpret_cast<char*>(&other->_impl_.error_code_));
}

::PROTOBUF_NAMESPACE_ID::Metadata BatteryMsg::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_msg_5fbattery_2eproto_getter, &descriptor_table_msg_5fbattery_2eproto_once,
      file_level_metadata_msg_5fbattery_2eproto[3]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace battery
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::battery::DCDCData*
Arena::CreateMaybeMessage< ::battery::DCDCData >(Arena* arena) {
  return Arena::CreateMessageInternal< ::battery::DCDCData >(arena);
}
template<> PROTOBUF_NOINLINE ::battery::PCSData*
Arena::CreateMaybeMessage< ::battery::PCSData >(Arena* arena) {
  return Arena::CreateMessageInternal< ::battery::PCSData >(arena);
}
template<> PROTOBUF_NOINLINE ::battery::OutBatteryMsg*
Arena::CreateMaybeMessage< ::battery::OutBatteryMsg >(Arena* arena) {
  return Arena::CreateMessageInternal< ::battery::OutBatteryMsg >(arena);
}
template<> PROTOBUF_NOINLINE ::battery::BatteryMsg*
Arena::CreateMaybeMessage< ::battery::BatteryMsg >(Arena* arena) {
  return Arena::CreateMessageInternal< ::battery::BatteryMsg >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
