// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: msg_battery.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_msg_5fbattery_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_msg_5fbattery_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_msg_5fbattery_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_msg_5fbattery_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_msg_5fbattery_2eproto;
namespace battery {
class BatteryMsg;
struct BatteryMsgDefaultTypeInternal;
extern BatteryMsgDefaultTypeInternal _BatteryMsg_default_instance_;
class DCDCData;
struct DCDCDataDefaultTypeInternal;
extern DCDCDataDefaultTypeInternal _DCDCData_default_instance_;
class OutBatteryMsg;
struct OutBatteryMsgDefaultTypeInternal;
extern OutBatteryMsgDefaultTypeInternal _OutBatteryMsg_default_instance_;
class PCSData;
struct PCSDataDefaultTypeInternal;
extern PCSDataDefaultTypeInternal _PCSData_default_instance_;
}  // namespace battery
PROTOBUF_NAMESPACE_OPEN
template<> ::battery::BatteryMsg* Arena::CreateMaybeMessage<::battery::BatteryMsg>(Arena*);
template<> ::battery::DCDCData* Arena::CreateMaybeMessage<::battery::DCDCData>(Arena*);
template<> ::battery::OutBatteryMsg* Arena::CreateMaybeMessage<::battery::OutBatteryMsg>(Arena*);
template<> ::battery::PCSData* Arena::CreateMaybeMessage<::battery::PCSData>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace battery {

enum DataStatus : int {
  ALL_NORMAL = 0,
  TIMEOUT = 1,
  CRC_ERROR = 2,
  INVALID_PARAM = 3,
  NOT_INIT = 4,
  HW_FAULT = 5,
  BUS_ERROR = 6,
  NO_RESPONSE = 7,
  OTHER_ERROR = 255,
  DataStatus_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::min(),
  DataStatus_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::max()
};
bool DataStatus_IsValid(int value);
constexpr DataStatus DataStatus_MIN = ALL_NORMAL;
constexpr DataStatus DataStatus_MAX = OTHER_ERROR;
constexpr int DataStatus_ARRAYSIZE = DataStatus_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* DataStatus_descriptor();
template<typename T>
inline const std::string& DataStatus_Name(T enum_t_value) {
  static_assert(::std::is_same<T, DataStatus>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function DataStatus_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    DataStatus_descriptor(), enum_t_value);
}
inline bool DataStatus_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, DataStatus* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<DataStatus>(
    DataStatus_descriptor(), name, value);
}
enum BatteryErrorCode : int {
  NO_ERROR = 0,
  CELL_OVER_VOLTAGE = 1,
  CELL_UNDER_VOLTAGE = 2,
  PACK_OVER_VOLTAGE = 4,
  PACK_UNDER_VOLTAGE = 8,
  CHARGE_OVER_TEMP = 16,
  CHARGE_LOW_TEMP = 32,
  DISCHARGE_OVER_TEMP = 64,
  DISCHARGE_LOW_TEMP = 128,
  CHARGE_OVER_CURRENT = 256,
  DISCHARGE_OVER_CURRENT = 512,
  SHORT_CIRCUIT = 1024,
  FRONT_END_IC_ERROR = 2048,
  SOFTWARE_LOCK_MOS = 4096,
  BatteryErrorCode_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::min(),
  BatteryErrorCode_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::max()
};
bool BatteryErrorCode_IsValid(int value);
constexpr BatteryErrorCode BatteryErrorCode_MIN = NO_ERROR;
constexpr BatteryErrorCode BatteryErrorCode_MAX = SOFTWARE_LOCK_MOS;
constexpr int BatteryErrorCode_ARRAYSIZE = BatteryErrorCode_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* BatteryErrorCode_descriptor();
template<typename T>
inline const std::string& BatteryErrorCode_Name(T enum_t_value) {
  static_assert(::std::is_same<T, BatteryErrorCode>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function BatteryErrorCode_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    BatteryErrorCode_descriptor(), enum_t_value);
}
inline bool BatteryErrorCode_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, BatteryErrorCode* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<BatteryErrorCode>(
    BatteryErrorCode_descriptor(), name, value);
}
// ===================================================================

class DCDCData final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:battery.DCDCData) */ {
 public:
  inline DCDCData() : DCDCData(nullptr) {}
  ~DCDCData() override;
  explicit PROTOBUF_CONSTEXPR DCDCData(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  DCDCData(const DCDCData& from);
  DCDCData(DCDCData&& from) noexcept
    : DCDCData() {
    *this = ::std::move(from);
  }

  inline DCDCData& operator=(const DCDCData& from) {
    CopyFrom(from);
    return *this;
  }
  inline DCDCData& operator=(DCDCData&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const DCDCData& default_instance() {
    return *internal_default_instance();
  }
  static inline const DCDCData* internal_default_instance() {
    return reinterpret_cast<const DCDCData*>(
               &_DCDCData_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(DCDCData& a, DCDCData& b) {
    a.Swap(&b);
  }
  inline void Swap(DCDCData* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(DCDCData* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  DCDCData* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<DCDCData>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const DCDCData& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const DCDCData& from) {
    DCDCData::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(DCDCData* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "battery.DCDCData";
  }
  protected:
  explicit DCDCData(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kStatusFieldNumber = 1,
    kBusVoltageFieldNumber = 2,
    kOutCurrentFieldNumber = 3,
    kOutPowerFieldNumber = 4,
    kTempFieldNumber = 5,
  };
  // uint32 status = 1;
  void clear_status();
  uint32_t status() const;
  void set_status(uint32_t value);
  private:
  uint32_t _internal_status() const;
  void _internal_set_status(uint32_t value);
  public:

  // uint32 bus_voltage = 2;
  void clear_bus_voltage();
  uint32_t bus_voltage() const;
  void set_bus_voltage(uint32_t value);
  private:
  uint32_t _internal_bus_voltage() const;
  void _internal_set_bus_voltage(uint32_t value);
  public:

  // int32 out_current = 3;
  void clear_out_current();
  int32_t out_current() const;
  void set_out_current(int32_t value);
  private:
  int32_t _internal_out_current() const;
  void _internal_set_out_current(int32_t value);
  public:

  // int32 out_power = 4;
  void clear_out_power();
  int32_t out_power() const;
  void set_out_power(int32_t value);
  private:
  int32_t _internal_out_power() const;
  void _internal_set_out_power(int32_t value);
  public:

  // int32 temp = 5;
  void clear_temp();
  int32_t temp() const;
  void set_temp(int32_t value);
  private:
  int32_t _internal_temp() const;
  void _internal_set_temp(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:battery.DCDCData)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    uint32_t status_;
    uint32_t bus_voltage_;
    int32_t out_current_;
    int32_t out_power_;
    int32_t temp_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_msg_5fbattery_2eproto;
};
// -------------------------------------------------------------------

class PCSData final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:battery.PCSData) */ {
 public:
  inline PCSData() : PCSData(nullptr) {}
  ~PCSData() override;
  explicit PROTOBUF_CONSTEXPR PCSData(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  PCSData(const PCSData& from);
  PCSData(PCSData&& from) noexcept
    : PCSData() {
    *this = ::std::move(from);
  }

  inline PCSData& operator=(const PCSData& from) {
    CopyFrom(from);
    return *this;
  }
  inline PCSData& operator=(PCSData&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const PCSData& default_instance() {
    return *internal_default_instance();
  }
  static inline const PCSData* internal_default_instance() {
    return reinterpret_cast<const PCSData*>(
               &_PCSData_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(PCSData& a, PCSData& b) {
    a.Swap(&b);
  }
  inline void Swap(PCSData* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(PCSData* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  PCSData* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<PCSData>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const PCSData& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const PCSData& from) {
    PCSData::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(PCSData* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "battery.PCSData";
  }
  protected:
  explicit PCSData(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kStatusFieldNumber = 1,
    kOutVoltageFieldNumber = 2,
    kOutCurrentFieldNumber = 3,
    kOutPowerFieldNumber = 4,
    kTempFieldNumber = 5,
  };
  // uint32 status = 1;
  void clear_status();
  uint32_t status() const;
  void set_status(uint32_t value);
  private:
  uint32_t _internal_status() const;
  void _internal_set_status(uint32_t value);
  public:

  // uint32 out_voltage = 2;
  void clear_out_voltage();
  uint32_t out_voltage() const;
  void set_out_voltage(uint32_t value);
  private:
  uint32_t _internal_out_voltage() const;
  void _internal_set_out_voltage(uint32_t value);
  public:

  // int32 out_current = 3;
  void clear_out_current();
  int32_t out_current() const;
  void set_out_current(int32_t value);
  private:
  int32_t _internal_out_current() const;
  void _internal_set_out_current(int32_t value);
  public:

  // int32 out_power = 4;
  void clear_out_power();
  int32_t out_power() const;
  void set_out_power(int32_t value);
  private:
  int32_t _internal_out_power() const;
  void _internal_set_out_power(int32_t value);
  public:

  // int32 temp = 5;
  void clear_temp();
  int32_t temp() const;
  void set_temp(int32_t value);
  private:
  int32_t _internal_temp() const;
  void _internal_set_temp(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:battery.PCSData)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    uint32_t status_;
    uint32_t out_voltage_;
    int32_t out_current_;
    int32_t out_power_;
    int32_t temp_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_msg_5fbattery_2eproto;
};
// -------------------------------------------------------------------

class OutBatteryMsg final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:battery.OutBatteryMsg) */ {
 public:
  inline OutBatteryMsg() : OutBatteryMsg(nullptr) {}
  ~OutBatteryMsg() override;
  explicit PROTOBUF_CONSTEXPR OutBatteryMsg(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  OutBatteryMsg(const OutBatteryMsg& from);
  OutBatteryMsg(OutBatteryMsg&& from) noexcept
    : OutBatteryMsg() {
    *this = ::std::move(from);
  }

  inline OutBatteryMsg& operator=(const OutBatteryMsg& from) {
    CopyFrom(from);
    return *this;
  }
  inline OutBatteryMsg& operator=(OutBatteryMsg&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const OutBatteryMsg& default_instance() {
    return *internal_default_instance();
  }
  static inline const OutBatteryMsg* internal_default_instance() {
    return reinterpret_cast<const OutBatteryMsg*>(
               &_OutBatteryMsg_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(OutBatteryMsg& a, OutBatteryMsg& b) {
    a.Swap(&b);
  }
  inline void Swap(OutBatteryMsg* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(OutBatteryMsg* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  OutBatteryMsg* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<OutBatteryMsg>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const OutBatteryMsg& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const OutBatteryMsg& from) {
    OutBatteryMsg::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(OutBatteryMsg* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "battery.OutBatteryMsg";
  }
  protected:
  explicit OutBatteryMsg(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kBatteriesFieldNumber = 3,
    kDcdcListFieldNumber = 9,
    kPcsListFieldNumber = 11,
    kPortFieldNumber = 1,
    kBatteryNumFieldNumber = 2,
    kPackVoltageFieldNumber = 4,
    kPackCurrentFieldNumber = 5,
    kPackRsocFieldNumber = 6,
    kPackAlarmFieldNumber = 7,
    kDcdcNumFieldNumber = 8,
    kPcsNumFieldNumber = 10,
  };
  // repeated .battery.BatteryMsg batteries = 3;
  int batteries_size() const;
  private:
  int _internal_batteries_size() const;
  public:
  void clear_batteries();
  ::battery::BatteryMsg* mutable_batteries(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::battery::BatteryMsg >*
      mutable_batteries();
  private:
  const ::battery::BatteryMsg& _internal_batteries(int index) const;
  ::battery::BatteryMsg* _internal_add_batteries();
  public:
  const ::battery::BatteryMsg& batteries(int index) const;
  ::battery::BatteryMsg* add_batteries();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::battery::BatteryMsg >&
      batteries() const;

  // repeated .battery.DCDCData dcdc_list = 9;
  int dcdc_list_size() const;
  private:
  int _internal_dcdc_list_size() const;
  public:
  void clear_dcdc_list();
  ::battery::DCDCData* mutable_dcdc_list(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::battery::DCDCData >*
      mutable_dcdc_list();
  private:
  const ::battery::DCDCData& _internal_dcdc_list(int index) const;
  ::battery::DCDCData* _internal_add_dcdc_list();
  public:
  const ::battery::DCDCData& dcdc_list(int index) const;
  ::battery::DCDCData* add_dcdc_list();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::battery::DCDCData >&
      dcdc_list() const;

  // repeated .battery.PCSData pcs_list = 11;
  int pcs_list_size() const;
  private:
  int _internal_pcs_list_size() const;
  public:
  void clear_pcs_list();
  ::battery::PCSData* mutable_pcs_list(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::battery::PCSData >*
      mutable_pcs_list();
  private:
  const ::battery::PCSData& _internal_pcs_list(int index) const;
  ::battery::PCSData* _internal_add_pcs_list();
  public:
  const ::battery::PCSData& pcs_list(int index) const;
  ::battery::PCSData* add_pcs_list();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::battery::PCSData >&
      pcs_list() const;

  // uint32 port = 1;
  void clear_port();
  uint32_t port() const;
  void set_port(uint32_t value);
  private:
  uint32_t _internal_port() const;
  void _internal_set_port(uint32_t value);
  public:

  // uint32 battery_num = 2;
  void clear_battery_num();
  uint32_t battery_num() const;
  void set_battery_num(uint32_t value);
  private:
  uint32_t _internal_battery_num() const;
  void _internal_set_battery_num(uint32_t value);
  public:

  // uint32 pack_voltage = 4;
  void clear_pack_voltage();
  uint32_t pack_voltage() const;
  void set_pack_voltage(uint32_t value);
  private:
  uint32_t _internal_pack_voltage() const;
  void _internal_set_pack_voltage(uint32_t value);
  public:

  // int32 pack_current = 5;
  void clear_pack_current();
  int32_t pack_current() const;
  void set_pack_current(int32_t value);
  private:
  int32_t _internal_pack_current() const;
  void _internal_set_pack_current(int32_t value);
  public:

  // uint32 pack_rsoc = 6;
  void clear_pack_rsoc();
  uint32_t pack_rsoc() const;
  void set_pack_rsoc(uint32_t value);
  private:
  uint32_t _internal_pack_rsoc() const;
  void _internal_set_pack_rsoc(uint32_t value);
  public:

  // bool pack_alarm = 7;
  void clear_pack_alarm();
  bool pack_alarm() const;
  void set_pack_alarm(bool value);
  private:
  bool _internal_pack_alarm() const;
  void _internal_set_pack_alarm(bool value);
  public:

  // uint32 dcdc_num = 8;
  void clear_dcdc_num();
  uint32_t dcdc_num() const;
  void set_dcdc_num(uint32_t value);
  private:
  uint32_t _internal_dcdc_num() const;
  void _internal_set_dcdc_num(uint32_t value);
  public:

  // uint32 pcs_num = 10;
  void clear_pcs_num();
  uint32_t pcs_num() const;
  void set_pcs_num(uint32_t value);
  private:
  uint32_t _internal_pcs_num() const;
  void _internal_set_pcs_num(uint32_t value);
  public:

  // @@protoc_insertion_point(class_scope:battery.OutBatteryMsg)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::battery::BatteryMsg > batteries_;
    ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::battery::DCDCData > dcdc_list_;
    ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::battery::PCSData > pcs_list_;
    uint32_t port_;
    uint32_t battery_num_;
    uint32_t pack_voltage_;
    int32_t pack_current_;
    uint32_t pack_rsoc_;
    bool pack_alarm_;
    uint32_t dcdc_num_;
    uint32_t pcs_num_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_msg_5fbattery_2eproto;
};
// -------------------------------------------------------------------

class BatteryMsg final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:battery.BatteryMsg) */ {
 public:
  inline BatteryMsg() : BatteryMsg(nullptr) {}
  ~BatteryMsg() override;
  explicit PROTOBUF_CONSTEXPR BatteryMsg(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  BatteryMsg(const BatteryMsg& from);
  BatteryMsg(BatteryMsg&& from) noexcept
    : BatteryMsg() {
    *this = ::std::move(from);
  }

  inline BatteryMsg& operator=(const BatteryMsg& from) {
    CopyFrom(from);
    return *this;
  }
  inline BatteryMsg& operator=(BatteryMsg&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const BatteryMsg& default_instance() {
    return *internal_default_instance();
  }
  static inline const BatteryMsg* internal_default_instance() {
    return reinterpret_cast<const BatteryMsg*>(
               &_BatteryMsg_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  friend void swap(BatteryMsg& a, BatteryMsg& b) {
    a.Swap(&b);
  }
  inline void Swap(BatteryMsg* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(BatteryMsg* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  BatteryMsg* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<BatteryMsg>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const BatteryMsg& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const BatteryMsg& from) {
    BatteryMsg::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(BatteryMsg* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "battery.BatteryMsg";
  }
  protected:
  explicit BatteryMsg(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kCellVoltagesFieldNumber = 10,
    kNtcTempsFieldNumber = 12,
    kErrorCodeFieldNumber = 2,
    kDataStatusFieldNumber = 1,
    kRsocFieldNumber = 3,
    kVoltageFieldNumber = 4,
    kCurrentFieldNumber = 5,
    kResidualCapacityFieldNumber = 6,
    kNominalCapacityFieldNumber = 7,
    kCycleCountFieldNumber = 8,
    kCellSeriesCountFieldNumber = 9,
    kNtcNumFieldNumber = 11,
  };
  // repeated uint32 cell_voltages = 10;
  int cell_voltages_size() const;
  private:
  int _internal_cell_voltages_size() const;
  public:
  void clear_cell_voltages();
  private:
  uint32_t _internal_cell_voltages(int index) const;
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< uint32_t >&
      _internal_cell_voltages() const;
  void _internal_add_cell_voltages(uint32_t value);
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< uint32_t >*
      _internal_mutable_cell_voltages();
  public:
  uint32_t cell_voltages(int index) const;
  void set_cell_voltages(int index, uint32_t value);
  void add_cell_voltages(uint32_t value);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< uint32_t >&
      cell_voltages() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< uint32_t >*
      mutable_cell_voltages();

  // repeated int32 ntc_temps = 12;
  int ntc_temps_size() const;
  private:
  int _internal_ntc_temps_size() const;
  public:
  void clear_ntc_temps();
  private:
  int32_t _internal_ntc_temps(int index) const;
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t >&
      _internal_ntc_temps() const;
  void _internal_add_ntc_temps(int32_t value);
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t >*
      _internal_mutable_ntc_temps();
  public:
  int32_t ntc_temps(int index) const;
  void set_ntc_temps(int index, int32_t value);
  void add_ntc_temps(int32_t value);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t >&
      ntc_temps() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t >*
      mutable_ntc_temps();

  // uint64 error_code = 2;
  void clear_error_code();
  uint64_t error_code() const;
  void set_error_code(uint64_t value);
  private:
  uint64_t _internal_error_code() const;
  void _internal_set_error_code(uint64_t value);
  public:

  // .battery.DataStatus data_status = 1;
  void clear_data_status();
  ::battery::DataStatus data_status() const;
  void set_data_status(::battery::DataStatus value);
  private:
  ::battery::DataStatus _internal_data_status() const;
  void _internal_set_data_status(::battery::DataStatus value);
  public:

  // uint32 rsoc = 3;
  void clear_rsoc();
  uint32_t rsoc() const;
  void set_rsoc(uint32_t value);
  private:
  uint32_t _internal_rsoc() const;
  void _internal_set_rsoc(uint32_t value);
  public:

  // uint32 voltage = 4;
  void clear_voltage();
  uint32_t voltage() const;
  void set_voltage(uint32_t value);
  private:
  uint32_t _internal_voltage() const;
  void _internal_set_voltage(uint32_t value);
  public:

  // int32 current = 5;
  void clear_current();
  int32_t current() const;
  void set_current(int32_t value);
  private:
  int32_t _internal_current() const;
  void _internal_set_current(int32_t value);
  public:

  // uint32 residual_capacity = 6;
  void clear_residual_capacity();
  uint32_t residual_capacity() const;
  void set_residual_capacity(uint32_t value);
  private:
  uint32_t _internal_residual_capacity() const;
  void _internal_set_residual_capacity(uint32_t value);
  public:

  // uint32 nominal_capacity = 7;
  void clear_nominal_capacity();
  uint32_t nominal_capacity() const;
  void set_nominal_capacity(uint32_t value);
  private:
  uint32_t _internal_nominal_capacity() const;
  void _internal_set_nominal_capacity(uint32_t value);
  public:

  // uint32 cycle_count = 8;
  void clear_cycle_count();
  uint32_t cycle_count() const;
  void set_cycle_count(uint32_t value);
  private:
  uint32_t _internal_cycle_count() const;
  void _internal_set_cycle_count(uint32_t value);
  public:

  // uint32 cell_series_count = 9;
  void clear_cell_series_count();
  uint32_t cell_series_count() const;
  void set_cell_series_count(uint32_t value);
  private:
  uint32_t _internal_cell_series_count() const;
  void _internal_set_cell_series_count(uint32_t value);
  public:

  // uint32 ntc_num = 11;
  void clear_ntc_num();
  uint32_t ntc_num() const;
  void set_ntc_num(uint32_t value);
  private:
  uint32_t _internal_ntc_num() const;
  void _internal_set_ntc_num(uint32_t value);
  public:

  // @@protoc_insertion_point(class_scope:battery.BatteryMsg)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::RepeatedField< uint32_t > cell_voltages_;
    mutable std::atomic<int> _cell_voltages_cached_byte_size_;
    ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t > ntc_temps_;
    mutable std::atomic<int> _ntc_temps_cached_byte_size_;
    uint64_t error_code_;
    int data_status_;
    uint32_t rsoc_;
    uint32_t voltage_;
    int32_t current_;
    uint32_t residual_capacity_;
    uint32_t nominal_capacity_;
    uint32_t cycle_count_;
    uint32_t cell_series_count_;
    uint32_t ntc_num_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_msg_5fbattery_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// DCDCData

// uint32 status = 1;
inline void DCDCData::clear_status() {
  _impl_.status_ = 0u;
}
inline uint32_t DCDCData::_internal_status() const {
  return _impl_.status_;
}
inline uint32_t DCDCData::status() const {
  // @@protoc_insertion_point(field_get:battery.DCDCData.status)
  return _internal_status();
}
inline void DCDCData::_internal_set_status(uint32_t value) {
  
  _impl_.status_ = value;
}
inline void DCDCData::set_status(uint32_t value) {
  _internal_set_status(value);
  // @@protoc_insertion_point(field_set:battery.DCDCData.status)
}

// uint32 bus_voltage = 2;
inline void DCDCData::clear_bus_voltage() {
  _impl_.bus_voltage_ = 0u;
}
inline uint32_t DCDCData::_internal_bus_voltage() const {
  return _impl_.bus_voltage_;
}
inline uint32_t DCDCData::bus_voltage() const {
  // @@protoc_insertion_point(field_get:battery.DCDCData.bus_voltage)
  return _internal_bus_voltage();
}
inline void DCDCData::_internal_set_bus_voltage(uint32_t value) {
  
  _impl_.bus_voltage_ = value;
}
inline void DCDCData::set_bus_voltage(uint32_t value) {
  _internal_set_bus_voltage(value);
  // @@protoc_insertion_point(field_set:battery.DCDCData.bus_voltage)
}

// int32 out_current = 3;
inline void DCDCData::clear_out_current() {
  _impl_.out_current_ = 0;
}
inline int32_t DCDCData::_internal_out_current() const {
  return _impl_.out_current_;
}
inline int32_t DCDCData::out_current() const {
  // @@protoc_insertion_point(field_get:battery.DCDCData.out_current)
  return _internal_out_current();
}
inline void DCDCData::_internal_set_out_current(int32_t value) {
  
  _impl_.out_current_ = value;
}
inline void DCDCData::set_out_current(int32_t value) {
  _internal_set_out_current(value);
  // @@protoc_insertion_point(field_set:battery.DCDCData.out_current)
}

// int32 out_power = 4;
inline void DCDCData::clear_out_power() {
  _impl_.out_power_ = 0;
}
inline int32_t DCDCData::_internal_out_power() const {
  return _impl_.out_power_;
}
inline int32_t DCDCData::out_power() const {
  // @@protoc_insertion_point(field_get:battery.DCDCData.out_power)
  return _internal_out_power();
}
inline void DCDCData::_internal_set_out_power(int32_t value) {
  
  _impl_.out_power_ = value;
}
inline void DCDCData::set_out_power(int32_t value) {
  _internal_set_out_power(value);
  // @@protoc_insertion_point(field_set:battery.DCDCData.out_power)
}

// int32 temp = 5;
inline void DCDCData::clear_temp() {
  _impl_.temp_ = 0;
}
inline int32_t DCDCData::_internal_temp() const {
  return _impl_.temp_;
}
inline int32_t DCDCData::temp() const {
  // @@protoc_insertion_point(field_get:battery.DCDCData.temp)
  return _internal_temp();
}
inline void DCDCData::_internal_set_temp(int32_t value) {
  
  _impl_.temp_ = value;
}
inline void DCDCData::set_temp(int32_t value) {
  _internal_set_temp(value);
  // @@protoc_insertion_point(field_set:battery.DCDCData.temp)
}

// -------------------------------------------------------------------

// PCSData

// uint32 status = 1;
inline void PCSData::clear_status() {
  _impl_.status_ = 0u;
}
inline uint32_t PCSData::_internal_status() const {
  return _impl_.status_;
}
inline uint32_t PCSData::status() const {
  // @@protoc_insertion_point(field_get:battery.PCSData.status)
  return _internal_status();
}
inline void PCSData::_internal_set_status(uint32_t value) {
  
  _impl_.status_ = value;
}
inline void PCSData::set_status(uint32_t value) {
  _internal_set_status(value);
  // @@protoc_insertion_point(field_set:battery.PCSData.status)
}

// uint32 out_voltage = 2;
inline void PCSData::clear_out_voltage() {
  _impl_.out_voltage_ = 0u;
}
inline uint32_t PCSData::_internal_out_voltage() const {
  return _impl_.out_voltage_;
}
inline uint32_t PCSData::out_voltage() const {
  // @@protoc_insertion_point(field_get:battery.PCSData.out_voltage)
  return _internal_out_voltage();
}
inline void PCSData::_internal_set_out_voltage(uint32_t value) {
  
  _impl_.out_voltage_ = value;
}
inline void PCSData::set_out_voltage(uint32_t value) {
  _internal_set_out_voltage(value);
  // @@protoc_insertion_point(field_set:battery.PCSData.out_voltage)
}

// int32 out_current = 3;
inline void PCSData::clear_out_current() {
  _impl_.out_current_ = 0;
}
inline int32_t PCSData::_internal_out_current() const {
  return _impl_.out_current_;
}
inline int32_t PCSData::out_current() const {
  // @@protoc_insertion_point(field_get:battery.PCSData.out_current)
  return _internal_out_current();
}
inline void PCSData::_internal_set_out_current(int32_t value) {
  
  _impl_.out_current_ = value;
}
inline void PCSData::set_out_current(int32_t value) {
  _internal_set_out_current(value);
  // @@protoc_insertion_point(field_set:battery.PCSData.out_current)
}

// int32 out_power = 4;
inline void PCSData::clear_out_power() {
  _impl_.out_power_ = 0;
}
inline int32_t PCSData::_internal_out_power() const {
  return _impl_.out_power_;
}
inline int32_t PCSData::out_power() const {
  // @@protoc_insertion_point(field_get:battery.PCSData.out_power)
  return _internal_out_power();
}
inline void PCSData::_internal_set_out_power(int32_t value) {
  
  _impl_.out_power_ = value;
}
inline void PCSData::set_out_power(int32_t value) {
  _internal_set_out_power(value);
  // @@protoc_insertion_point(field_set:battery.PCSData.out_power)
}

// int32 temp = 5;
inline void PCSData::clear_temp() {
  _impl_.temp_ = 0;
}
inline int32_t PCSData::_internal_temp() const {
  return _impl_.temp_;
}
inline int32_t PCSData::temp() const {
  // @@protoc_insertion_point(field_get:battery.PCSData.temp)
  return _internal_temp();
}
inline void PCSData::_internal_set_temp(int32_t value) {
  
  _impl_.temp_ = value;
}
inline void PCSData::set_temp(int32_t value) {
  _internal_set_temp(value);
  // @@protoc_insertion_point(field_set:battery.PCSData.temp)
}

// -------------------------------------------------------------------

// OutBatteryMsg

// uint32 port = 1;
inline void OutBatteryMsg::clear_port() {
  _impl_.port_ = 0u;
}
inline uint32_t OutBatteryMsg::_internal_port() const {
  return _impl_.port_;
}
inline uint32_t OutBatteryMsg::port() const {
  // @@protoc_insertion_point(field_get:battery.OutBatteryMsg.port)
  return _internal_port();
}
inline void OutBatteryMsg::_internal_set_port(uint32_t value) {
  
  _impl_.port_ = value;
}
inline void OutBatteryMsg::set_port(uint32_t value) {
  _internal_set_port(value);
  // @@protoc_insertion_point(field_set:battery.OutBatteryMsg.port)
}

// uint32 battery_num = 2;
inline void OutBatteryMsg::clear_battery_num() {
  _impl_.battery_num_ = 0u;
}
inline uint32_t OutBatteryMsg::_internal_battery_num() const {
  return _impl_.battery_num_;
}
inline uint32_t OutBatteryMsg::battery_num() const {
  // @@protoc_insertion_point(field_get:battery.OutBatteryMsg.battery_num)
  return _internal_battery_num();
}
inline void OutBatteryMsg::_internal_set_battery_num(uint32_t value) {
  
  _impl_.battery_num_ = value;
}
inline void OutBatteryMsg::set_battery_num(uint32_t value) {
  _internal_set_battery_num(value);
  // @@protoc_insertion_point(field_set:battery.OutBatteryMsg.battery_num)
}

// repeated .battery.BatteryMsg batteries = 3;
inline int OutBatteryMsg::_internal_batteries_size() const {
  return _impl_.batteries_.size();
}
inline int OutBatteryMsg::batteries_size() const {
  return _internal_batteries_size();
}
inline void OutBatteryMsg::clear_batteries() {
  _impl_.batteries_.Clear();
}
inline ::battery::BatteryMsg* OutBatteryMsg::mutable_batteries(int index) {
  // @@protoc_insertion_point(field_mutable:battery.OutBatteryMsg.batteries)
  return _impl_.batteries_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::battery::BatteryMsg >*
OutBatteryMsg::mutable_batteries() {
  // @@protoc_insertion_point(field_mutable_list:battery.OutBatteryMsg.batteries)
  return &_impl_.batteries_;
}
inline const ::battery::BatteryMsg& OutBatteryMsg::_internal_batteries(int index) const {
  return _impl_.batteries_.Get(index);
}
inline const ::battery::BatteryMsg& OutBatteryMsg::batteries(int index) const {
  // @@protoc_insertion_point(field_get:battery.OutBatteryMsg.batteries)
  return _internal_batteries(index);
}
inline ::battery::BatteryMsg* OutBatteryMsg::_internal_add_batteries() {
  return _impl_.batteries_.Add();
}
inline ::battery::BatteryMsg* OutBatteryMsg::add_batteries() {
  ::battery::BatteryMsg* _add = _internal_add_batteries();
  // @@protoc_insertion_point(field_add:battery.OutBatteryMsg.batteries)
  return _add;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::battery::BatteryMsg >&
OutBatteryMsg::batteries() const {
  // @@protoc_insertion_point(field_list:battery.OutBatteryMsg.batteries)
  return _impl_.batteries_;
}

// uint32 pack_voltage = 4;
inline void OutBatteryMsg::clear_pack_voltage() {
  _impl_.pack_voltage_ = 0u;
}
inline uint32_t OutBatteryMsg::_internal_pack_voltage() const {
  return _impl_.pack_voltage_;
}
inline uint32_t OutBatteryMsg::pack_voltage() const {
  // @@protoc_insertion_point(field_get:battery.OutBatteryMsg.pack_voltage)
  return _internal_pack_voltage();
}
inline void OutBatteryMsg::_internal_set_pack_voltage(uint32_t value) {
  
  _impl_.pack_voltage_ = value;
}
inline void OutBatteryMsg::set_pack_voltage(uint32_t value) {
  _internal_set_pack_voltage(value);
  // @@protoc_insertion_point(field_set:battery.OutBatteryMsg.pack_voltage)
}

// int32 pack_current = 5;
inline void OutBatteryMsg::clear_pack_current() {
  _impl_.pack_current_ = 0;
}
inline int32_t OutBatteryMsg::_internal_pack_current() const {
  return _impl_.pack_current_;
}
inline int32_t OutBatteryMsg::pack_current() const {
  // @@protoc_insertion_point(field_get:battery.OutBatteryMsg.pack_current)
  return _internal_pack_current();
}
inline void OutBatteryMsg::_internal_set_pack_current(int32_t value) {
  
  _impl_.pack_current_ = value;
}
inline void OutBatteryMsg::set_pack_current(int32_t value) {
  _internal_set_pack_current(value);
  // @@protoc_insertion_point(field_set:battery.OutBatteryMsg.pack_current)
}

// uint32 pack_rsoc = 6;
inline void OutBatteryMsg::clear_pack_rsoc() {
  _impl_.pack_rsoc_ = 0u;
}
inline uint32_t OutBatteryMsg::_internal_pack_rsoc() const {
  return _impl_.pack_rsoc_;
}
inline uint32_t OutBatteryMsg::pack_rsoc() const {
  // @@protoc_insertion_point(field_get:battery.OutBatteryMsg.pack_rsoc)
  return _internal_pack_rsoc();
}
inline void OutBatteryMsg::_internal_set_pack_rsoc(uint32_t value) {
  
  _impl_.pack_rsoc_ = value;
}
inline void OutBatteryMsg::set_pack_rsoc(uint32_t value) {
  _internal_set_pack_rsoc(value);
  // @@protoc_insertion_point(field_set:battery.OutBatteryMsg.pack_rsoc)
}

// bool pack_alarm = 7;
inline void OutBatteryMsg::clear_pack_alarm() {
  _impl_.pack_alarm_ = false;
}
inline bool OutBatteryMsg::_internal_pack_alarm() const {
  return _impl_.pack_alarm_;
}
inline bool OutBatteryMsg::pack_alarm() const {
  // @@protoc_insertion_point(field_get:battery.OutBatteryMsg.pack_alarm)
  return _internal_pack_alarm();
}
inline void OutBatteryMsg::_internal_set_pack_alarm(bool value) {
  
  _impl_.pack_alarm_ = value;
}
inline void OutBatteryMsg::set_pack_alarm(bool value) {
  _internal_set_pack_alarm(value);
  // @@protoc_insertion_point(field_set:battery.OutBatteryMsg.pack_alarm)
}

// uint32 dcdc_num = 8;
inline void OutBatteryMsg::clear_dcdc_num() {
  _impl_.dcdc_num_ = 0u;
}
inline uint32_t OutBatteryMsg::_internal_dcdc_num() const {
  return _impl_.dcdc_num_;
}
inline uint32_t OutBatteryMsg::dcdc_num() const {
  // @@protoc_insertion_point(field_get:battery.OutBatteryMsg.dcdc_num)
  return _internal_dcdc_num();
}
inline void OutBatteryMsg::_internal_set_dcdc_num(uint32_t value) {
  
  _impl_.dcdc_num_ = value;
}
inline void OutBatteryMsg::set_dcdc_num(uint32_t value) {
  _internal_set_dcdc_num(value);
  // @@protoc_insertion_point(field_set:battery.OutBatteryMsg.dcdc_num)
}

// repeated .battery.DCDCData dcdc_list = 9;
inline int OutBatteryMsg::_internal_dcdc_list_size() const {
  return _impl_.dcdc_list_.size();
}
inline int OutBatteryMsg::dcdc_list_size() const {
  return _internal_dcdc_list_size();
}
inline void OutBatteryMsg::clear_dcdc_list() {
  _impl_.dcdc_list_.Clear();
}
inline ::battery::DCDCData* OutBatteryMsg::mutable_dcdc_list(int index) {
  // @@protoc_insertion_point(field_mutable:battery.OutBatteryMsg.dcdc_list)
  return _impl_.dcdc_list_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::battery::DCDCData >*
OutBatteryMsg::mutable_dcdc_list() {
  // @@protoc_insertion_point(field_mutable_list:battery.OutBatteryMsg.dcdc_list)
  return &_impl_.dcdc_list_;
}
inline const ::battery::DCDCData& OutBatteryMsg::_internal_dcdc_list(int index) const {
  return _impl_.dcdc_list_.Get(index);
}
inline const ::battery::DCDCData& OutBatteryMsg::dcdc_list(int index) const {
  // @@protoc_insertion_point(field_get:battery.OutBatteryMsg.dcdc_list)
  return _internal_dcdc_list(index);
}
inline ::battery::DCDCData* OutBatteryMsg::_internal_add_dcdc_list() {
  return _impl_.dcdc_list_.Add();
}
inline ::battery::DCDCData* OutBatteryMsg::add_dcdc_list() {
  ::battery::DCDCData* _add = _internal_add_dcdc_list();
  // @@protoc_insertion_point(field_add:battery.OutBatteryMsg.dcdc_list)
  return _add;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::battery::DCDCData >&
OutBatteryMsg::dcdc_list() const {
  // @@protoc_insertion_point(field_list:battery.OutBatteryMsg.dcdc_list)
  return _impl_.dcdc_list_;
}

// uint32 pcs_num = 10;
inline void OutBatteryMsg::clear_pcs_num() {
  _impl_.pcs_num_ = 0u;
}
inline uint32_t OutBatteryMsg::_internal_pcs_num() const {
  return _impl_.pcs_num_;
}
inline uint32_t OutBatteryMsg::pcs_num() const {
  // @@protoc_insertion_point(field_get:battery.OutBatteryMsg.pcs_num)
  return _internal_pcs_num();
}
inline void OutBatteryMsg::_internal_set_pcs_num(uint32_t value) {
  
  _impl_.pcs_num_ = value;
}
inline void OutBatteryMsg::set_pcs_num(uint32_t value) {
  _internal_set_pcs_num(value);
  // @@protoc_insertion_point(field_set:battery.OutBatteryMsg.pcs_num)
}

// repeated .battery.PCSData pcs_list = 11;
inline int OutBatteryMsg::_internal_pcs_list_size() const {
  return _impl_.pcs_list_.size();
}
inline int OutBatteryMsg::pcs_list_size() const {
  return _internal_pcs_list_size();
}
inline void OutBatteryMsg::clear_pcs_list() {
  _impl_.pcs_list_.Clear();
}
inline ::battery::PCSData* OutBatteryMsg::mutable_pcs_list(int index) {
  // @@protoc_insertion_point(field_mutable:battery.OutBatteryMsg.pcs_list)
  return _impl_.pcs_list_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::battery::PCSData >*
OutBatteryMsg::mutable_pcs_list() {
  // @@protoc_insertion_point(field_mutable_list:battery.OutBatteryMsg.pcs_list)
  return &_impl_.pcs_list_;
}
inline const ::battery::PCSData& OutBatteryMsg::_internal_pcs_list(int index) const {
  return _impl_.pcs_list_.Get(index);
}
inline const ::battery::PCSData& OutBatteryMsg::pcs_list(int index) const {
  // @@protoc_insertion_point(field_get:battery.OutBatteryMsg.pcs_list)
  return _internal_pcs_list(index);
}
inline ::battery::PCSData* OutBatteryMsg::_internal_add_pcs_list() {
  return _impl_.pcs_list_.Add();
}
inline ::battery::PCSData* OutBatteryMsg::add_pcs_list() {
  ::battery::PCSData* _add = _internal_add_pcs_list();
  // @@protoc_insertion_point(field_add:battery.OutBatteryMsg.pcs_list)
  return _add;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::battery::PCSData >&
OutBatteryMsg::pcs_list() const {
  // @@protoc_insertion_point(field_list:battery.OutBatteryMsg.pcs_list)
  return _impl_.pcs_list_;
}

// -------------------------------------------------------------------

// BatteryMsg

// .battery.DataStatus data_status = 1;
inline void BatteryMsg::clear_data_status() {
  _impl_.data_status_ = 0;
}
inline ::battery::DataStatus BatteryMsg::_internal_data_status() const {
  return static_cast< ::battery::DataStatus >(_impl_.data_status_);
}
inline ::battery::DataStatus BatteryMsg::data_status() const {
  // @@protoc_insertion_point(field_get:battery.BatteryMsg.data_status)
  return _internal_data_status();
}
inline void BatteryMsg::_internal_set_data_status(::battery::DataStatus value) {
  
  _impl_.data_status_ = value;
}
inline void BatteryMsg::set_data_status(::battery::DataStatus value) {
  _internal_set_data_status(value);
  // @@protoc_insertion_point(field_set:battery.BatteryMsg.data_status)
}

// uint64 error_code = 2;
inline void BatteryMsg::clear_error_code() {
  _impl_.error_code_ = uint64_t{0u};
}
inline uint64_t BatteryMsg::_internal_error_code() const {
  return _impl_.error_code_;
}
inline uint64_t BatteryMsg::error_code() const {
  // @@protoc_insertion_point(field_get:battery.BatteryMsg.error_code)
  return _internal_error_code();
}
inline void BatteryMsg::_internal_set_error_code(uint64_t value) {
  
  _impl_.error_code_ = value;
}
inline void BatteryMsg::set_error_code(uint64_t value) {
  _internal_set_error_code(value);
  // @@protoc_insertion_point(field_set:battery.BatteryMsg.error_code)
}

// uint32 rsoc = 3;
inline void BatteryMsg::clear_rsoc() {
  _impl_.rsoc_ = 0u;
}
inline uint32_t BatteryMsg::_internal_rsoc() const {
  return _impl_.rsoc_;
}
inline uint32_t BatteryMsg::rsoc() const {
  // @@protoc_insertion_point(field_get:battery.BatteryMsg.rsoc)
  return _internal_rsoc();
}
inline void BatteryMsg::_internal_set_rsoc(uint32_t value) {
  
  _impl_.rsoc_ = value;
}
inline void BatteryMsg::set_rsoc(uint32_t value) {
  _internal_set_rsoc(value);
  // @@protoc_insertion_point(field_set:battery.BatteryMsg.rsoc)
}

// uint32 voltage = 4;
inline void BatteryMsg::clear_voltage() {
  _impl_.voltage_ = 0u;
}
inline uint32_t BatteryMsg::_internal_voltage() const {
  return _impl_.voltage_;
}
inline uint32_t BatteryMsg::voltage() const {
  // @@protoc_insertion_point(field_get:battery.BatteryMsg.voltage)
  return _internal_voltage();
}
inline void BatteryMsg::_internal_set_voltage(uint32_t value) {
  
  _impl_.voltage_ = value;
}
inline void BatteryMsg::set_voltage(uint32_t value) {
  _internal_set_voltage(value);
  // @@protoc_insertion_point(field_set:battery.BatteryMsg.voltage)
}

// int32 current = 5;
inline void BatteryMsg::clear_current() {
  _impl_.current_ = 0;
}
inline int32_t BatteryMsg::_internal_current() const {
  return _impl_.current_;
}
inline int32_t BatteryMsg::current() const {
  // @@protoc_insertion_point(field_get:battery.BatteryMsg.current)
  return _internal_current();
}
inline void BatteryMsg::_internal_set_current(int32_t value) {
  
  _impl_.current_ = value;
}
inline void BatteryMsg::set_current(int32_t value) {
  _internal_set_current(value);
  // @@protoc_insertion_point(field_set:battery.BatteryMsg.current)
}

// uint32 residual_capacity = 6;
inline void BatteryMsg::clear_residual_capacity() {
  _impl_.residual_capacity_ = 0u;
}
inline uint32_t BatteryMsg::_internal_residual_capacity() const {
  return _impl_.residual_capacity_;
}
inline uint32_t BatteryMsg::residual_capacity() const {
  // @@protoc_insertion_point(field_get:battery.BatteryMsg.residual_capacity)
  return _internal_residual_capacity();
}
inline void BatteryMsg::_internal_set_residual_capacity(uint32_t value) {
  
  _impl_.residual_capacity_ = value;
}
inline void BatteryMsg::set_residual_capacity(uint32_t value) {
  _internal_set_residual_capacity(value);
  // @@protoc_insertion_point(field_set:battery.BatteryMsg.residual_capacity)
}

// uint32 nominal_capacity = 7;
inline void BatteryMsg::clear_nominal_capacity() {
  _impl_.nominal_capacity_ = 0u;
}
inline uint32_t BatteryMsg::_internal_nominal_capacity() const {
  return _impl_.nominal_capacity_;
}
inline uint32_t BatteryMsg::nominal_capacity() const {
  // @@protoc_insertion_point(field_get:battery.BatteryMsg.nominal_capacity)
  return _internal_nominal_capacity();
}
inline void BatteryMsg::_internal_set_nominal_capacity(uint32_t value) {
  
  _impl_.nominal_capacity_ = value;
}
inline void BatteryMsg::set_nominal_capacity(uint32_t value) {
  _internal_set_nominal_capacity(value);
  // @@protoc_insertion_point(field_set:battery.BatteryMsg.nominal_capacity)
}

// uint32 cycle_count = 8;
inline void BatteryMsg::clear_cycle_count() {
  _impl_.cycle_count_ = 0u;
}
inline uint32_t BatteryMsg::_internal_cycle_count() const {
  return _impl_.cycle_count_;
}
inline uint32_t BatteryMsg::cycle_count() const {
  // @@protoc_insertion_point(field_get:battery.BatteryMsg.cycle_count)
  return _internal_cycle_count();
}
inline void BatteryMsg::_internal_set_cycle_count(uint32_t value) {
  
  _impl_.cycle_count_ = value;
}
inline void BatteryMsg::set_cycle_count(uint32_t value) {
  _internal_set_cycle_count(value);
  // @@protoc_insertion_point(field_set:battery.BatteryMsg.cycle_count)
}

// uint32 cell_series_count = 9;
inline void BatteryMsg::clear_cell_series_count() {
  _impl_.cell_series_count_ = 0u;
}
inline uint32_t BatteryMsg::_internal_cell_series_count() const {
  return _impl_.cell_series_count_;
}
inline uint32_t BatteryMsg::cell_series_count() const {
  // @@protoc_insertion_point(field_get:battery.BatteryMsg.cell_series_count)
  return _internal_cell_series_count();
}
inline void BatteryMsg::_internal_set_cell_series_count(uint32_t value) {
  
  _impl_.cell_series_count_ = value;
}
inline void BatteryMsg::set_cell_series_count(uint32_t value) {
  _internal_set_cell_series_count(value);
  // @@protoc_insertion_point(field_set:battery.BatteryMsg.cell_series_count)
}

// repeated uint32 cell_voltages = 10;
inline int BatteryMsg::_internal_cell_voltages_size() const {
  return _impl_.cell_voltages_.size();
}
inline int BatteryMsg::cell_voltages_size() const {
  return _internal_cell_voltages_size();
}
inline void BatteryMsg::clear_cell_voltages() {
  _impl_.cell_voltages_.Clear();
}
inline uint32_t BatteryMsg::_internal_cell_voltages(int index) const {
  return _impl_.cell_voltages_.Get(index);
}
inline uint32_t BatteryMsg::cell_voltages(int index) const {
  // @@protoc_insertion_point(field_get:battery.BatteryMsg.cell_voltages)
  return _internal_cell_voltages(index);
}
inline void BatteryMsg::set_cell_voltages(int index, uint32_t value) {
  _impl_.cell_voltages_.Set(index, value);
  // @@protoc_insertion_point(field_set:battery.BatteryMsg.cell_voltages)
}
inline void BatteryMsg::_internal_add_cell_voltages(uint32_t value) {
  _impl_.cell_voltages_.Add(value);
}
inline void BatteryMsg::add_cell_voltages(uint32_t value) {
  _internal_add_cell_voltages(value);
  // @@protoc_insertion_point(field_add:battery.BatteryMsg.cell_voltages)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< uint32_t >&
BatteryMsg::_internal_cell_voltages() const {
  return _impl_.cell_voltages_;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< uint32_t >&
BatteryMsg::cell_voltages() const {
  // @@protoc_insertion_point(field_list:battery.BatteryMsg.cell_voltages)
  return _internal_cell_voltages();
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< uint32_t >*
BatteryMsg::_internal_mutable_cell_voltages() {
  return &_impl_.cell_voltages_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< uint32_t >*
BatteryMsg::mutable_cell_voltages() {
  // @@protoc_insertion_point(field_mutable_list:battery.BatteryMsg.cell_voltages)
  return _internal_mutable_cell_voltages();
}

// uint32 ntc_num = 11;
inline void BatteryMsg::clear_ntc_num() {
  _impl_.ntc_num_ = 0u;
}
inline uint32_t BatteryMsg::_internal_ntc_num() const {
  return _impl_.ntc_num_;
}
inline uint32_t BatteryMsg::ntc_num() const {
  // @@protoc_insertion_point(field_get:battery.BatteryMsg.ntc_num)
  return _internal_ntc_num();
}
inline void BatteryMsg::_internal_set_ntc_num(uint32_t value) {
  
  _impl_.ntc_num_ = value;
}
inline void BatteryMsg::set_ntc_num(uint32_t value) {
  _internal_set_ntc_num(value);
  // @@protoc_insertion_point(field_set:battery.BatteryMsg.ntc_num)
}

// repeated int32 ntc_temps = 12;
inline int BatteryMsg::_internal_ntc_temps_size() const {
  return _impl_.ntc_temps_.size();
}
inline int BatteryMsg::ntc_temps_size() const {
  return _internal_ntc_temps_size();
}
inline void BatteryMsg::clear_ntc_temps() {
  _impl_.ntc_temps_.Clear();
}
inline int32_t BatteryMsg::_internal_ntc_temps(int index) const {
  return _impl_.ntc_temps_.Get(index);
}
inline int32_t BatteryMsg::ntc_temps(int index) const {
  // @@protoc_insertion_point(field_get:battery.BatteryMsg.ntc_temps)
  return _internal_ntc_temps(index);
}
inline void BatteryMsg::set_ntc_temps(int index, int32_t value) {
  _impl_.ntc_temps_.Set(index, value);
  // @@protoc_insertion_point(field_set:battery.BatteryMsg.ntc_temps)
}
inline void BatteryMsg::_internal_add_ntc_temps(int32_t value) {
  _impl_.ntc_temps_.Add(value);
}
inline void BatteryMsg::add_ntc_temps(int32_t value) {
  _internal_add_ntc_temps(value);
  // @@protoc_insertion_point(field_add:battery.BatteryMsg.ntc_temps)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t >&
BatteryMsg::_internal_ntc_temps() const {
  return _impl_.ntc_temps_;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t >&
BatteryMsg::ntc_temps() const {
  // @@protoc_insertion_point(field_list:battery.BatteryMsg.ntc_temps)
  return _internal_ntc_temps();
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t >*
BatteryMsg::_internal_mutable_ntc_temps() {
  return &_impl_.ntc_temps_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t >*
BatteryMsg::mutable_ntc_temps() {
  // @@protoc_insertion_point(field_mutable_list:battery.BatteryMsg.ntc_temps)
  return _internal_mutable_ntc_temps();
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace battery

PROTOBUF_NAMESPACE_OPEN

template <> struct is_proto_enum< ::battery::DataStatus> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::battery::DataStatus>() {
  return ::battery::DataStatus_descriptor();
}
template <> struct is_proto_enum< ::battery::BatteryErrorCode> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::battery::BatteryErrorCode>() {
  return ::battery::BatteryErrorCode_descriptor();
}

PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_msg_5fbattery_2eproto
